"""The SOUP evidence set must match the sources it summarises.

``docs/validation/soup_package.md`` and
``docs/validation/framework_verification.md`` carry summary tables of
``known_anomalies.yaml``, the ``@verification_benchmark`` registry and
``pyproject.toml``.  They were hand-maintained and drifted: 2 of 5
anomalies, 1 of 4 registered benchmarks, 7 of 12 test packages, and a
version identification two to three releases behind the package.  For
IEC 62304 evidence, drift is itself the finding.

The tables are now generated by ``scripts/generate_soup_tables.py``.
This module runs that script's ``--check`` mode, so a stale table fails
in CI's existing ``pytest tests/compliance/`` step rather than shipping.

The checks could later fold into ``scripts/check_anomalies.py``, which
CI's ``compliance`` job already runs; they live here because that script
was being rewritten concurrently.
"""

from __future__ import annotations

import difflib
import os
import subprocess
import sys
from pathlib import Path

import pytest

os.environ.setdefault("JAX_PLATFORMS", "cpu")

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_soup_tables.py"

sys.path.insert(0, str(REPO_ROOT / "scripts"))

import generate_soup_tables as gen  # noqa: E402


def _run_check() -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ, "JAX_PLATFORMS": "cpu"},
    )


def test_the_committed_soup_tables_match_a_fresh_generation():
    """A table that has drifted from its source fails here, not in review.

    This message deliberately does *not* tell you to regenerate and commit.
    It used to, and the generator's own error said the same thing, so the
    instruction was the same whichever kind of drift had occurred.  When the
    committed document holds a row the source no longer produces -- an
    anomaly deleted from the registry, a benchmark ID overwritten by a
    duplicate decorator -- regenerating removes that row from the evidence
    set and turns every gate green.  The generator now classifies the drift;
    read what it says before running anything.
    """
    result = _run_check()
    assert result.returncode == 0, (
        "The SOUP evidence set does not match the sources it summarises.  "
        "The generator's report below says which KIND of difference it found "
        "— a row missing from the committed document is not the same "
        "defect as a row the source has stopped producing, and only the "
        "first is fixed by regenerating.\n\n"
        + result.stdout + result.stderr
    )


# ---------------------------------------------------------------------------
# Registry membership: the document -> registry direction
# ---------------------------------------------------------------------------
# Every other check in this file runs registry -> document.  Nothing ran the
# other way and nothing pinned either registry's size or ID set, so an entry
# could be deleted from the source and the evidence set regenerated around the
# hole: 188 compliance tests green, the anomaly gone from soup_package.md
# (audit_040_r2/gates, finding G5).  Both ID spaces are contiguous, which is
# what makes a committed high-water mark a complete pin.
#
# These constants fail on a deletion AND on an unannounced addition.  The
# second is deliberate: adding an anomaly or a benchmark is a considered act,
# and bumping the number here is part of it.
#
# RETIRING AN ID: never delete the entry and never reuse the number.  Put the
# ID in the matching ``_RETIRED_*`` frozenset below, with a comment saying
# what was retired and when.  The number stays spoken for, the high-water mark
# stays honest, and the retirement is a visible line in the diff instead of a
# gap nobody can account for.
_HIGHEST_ANOMALY_ID = 23
_RETIRED_ANOMALY_IDS: frozenset = frozenset()

_HIGHEST_BENCHMARK_ID = 15
_RETIRED_BENCHMARK_IDS: frozenset = frozenset()


def _expected_ids(prefix: str, highest: int, retired: frozenset) -> set:
    return {f"{prefix}{n:03d}" for n in range(1, highest + 1)} - set(retired)


def _membership_message(kind: str, missing: set, unexpected: set) -> str:
    parts = []
    if missing:
        parts.append(
            f"{kind} missing from the registry: {sorted(missing)}.  An entry "
            f"in the committed set is IEC 62304 evidence; restore it, or "
            f"record the retirement in the _RETIRED_* frozenset in "
            f"tests/compliance/test_soup_evidence.py rather than deleting it."
        )
    if unexpected:
        parts.append(
            f"{kind} in the registry but not in the committed set: "
            f"{sorted(unexpected)}.  Raise the high-water mark in "
            f"tests/compliance/test_soup_evidence.py in the same commit that "
            f"adds the entry."
        )
    return "  ".join(parts)


def test_the_anomaly_registry_holds_exactly_the_committed_id_set():
    """Deleting an anomaly must turn something red before the generator runs."""
    actual = {a["anomaly_id"] for a in gen.read_registry()["anomalies"]}
    expected = _expected_ids(
        "MADD-ANO-", _HIGHEST_ANOMALY_ID, _RETIRED_ANOMALY_IDS
    )
    assert actual == expected, _membership_message(
        "anomaly ID(s)", expected - actual, actual - expected
    )


def test_the_benchmark_registry_holds_exactly_the_committed_id_set():
    """The same pin for ``@verification_benchmark``.

    A duplicate ``benchmark_id`` now raises at import time, but this is the
    pin that does not depend on *how* an entry went missing: a decorator
    deleted, a module dropped from ``BENCHMARK_MODULES``, or a test file
    removed all land here.
    """
    actual = set(gen.load_benchmarks())
    expected = _expected_ids(
        "MADD-VER-", _HIGHEST_BENCHMARK_ID, _RETIRED_BENCHMARK_IDS
    )
    assert actual == expected, _membership_message(
        "benchmark ID(s)", expected - actual, actual - expected
    )


def test_a_retired_id_is_recorded_and_not_reused():
    """A retired ID stays retired: absent from the registry, inside the range.

    An ID outside the high-water mark in ``_RETIRED_*`` is a typo, and one
    still present in the registry means the retirement never happened.
    """
    for label, retired, highest, registry_ids in (
        ("anomaly", _RETIRED_ANOMALY_IDS, _HIGHEST_ANOMALY_ID,
         {a["anomaly_id"] for a in gen.read_registry()["anomalies"]}),
        ("benchmark", _RETIRED_BENCHMARK_IDS, _HIGHEST_BENCHMARK_ID,
         set(gen.load_benchmarks())),
    ):
        for rid in retired:
            number = int(rid.rsplit("-", 1)[1])
            assert 1 <= number <= highest, (
                f"retired {label} ID {rid} is outside 1..{highest}"
            )
            assert rid not in registry_ids, (
                f"{rid} is recorded as a retired {label} ID but is still in "
                f"the registry"
            )


def test_every_anomaly_in_the_registry_reaches_the_summary_table():
    """The §3 table is complete, whatever the generator did to format it."""
    registry = gen.read_registry()
    rendered = gen.SOUP_PACKAGE.read_text()
    for anomaly in registry["anomalies"]:
        assert anomaly["anomaly_id"] in rendered, (
            f"{anomaly['anomaly_id']} is in known_anomalies.yaml but not in "
            f"soup_package.md"
        )


def test_every_registered_benchmark_reaches_the_verification_index():
    """The verification index is complete against the live registry."""
    benchmarks = gen.load_benchmarks()
    assert benchmarks, "no MADD-VER benchmarks registered — check the imports"
    rendered = gen.FRAMEWORK_VERIFICATION.read_text()
    for benchmark_id in benchmarks:
        assert benchmark_id in rendered, (
            f"{benchmark_id} is registered but missing from "
            f"framework_verification.md"
        )


def test_a_test_module_that_registers_a_benchmark_is_wired_into_the_index():
    """A new benchmark cannot register without joining BENCHMARK_MODULES.

    Without this the index stays green while going incomplete, which is
    how MADD-VER-002/003/004 ended up unlisted.
    """
    assert gen._check_benchmark_modules_are_complete() == []


def test_every_test_package_is_described_in_the_organization_table():
    assert gen._check_test_directories_are_described(gen.test_packages()) == []


def test_the_version_is_identified_the_same_way_everywhere():
    """pyproject is authoritative; the registry and CITATION.cff follow it."""
    assert gen._check_versions(
        gen.read_pyproject(), gen.read_registry(), gen.read_citation()
    ) == []


def test_every_version_range_agrees_with_its_entrys_status():
    """A reachable defect and a range that leaves this version out cannot
    both be true, and nor can a resolved one and a range that keeps it in.

    MADD-ANO-001 and MADD-ANO-002 sat `open` with a closed range for three
    releases.  MADD-ANO-005 was `partially_resolved` with `<=0.3.0`, and
    MADD-ANO-016 shipped `partially_resolved` with `>=0.1.0, <0.4.0` -- a
    range this check's old `startswith(">=")` test waved through -- while
    MADD-ANO-006 shipped `resolved` in 0.4.0 with `>=0.1.0`.  The rule now
    compares each range with the registry's own version (PEP 440), and is
    the registry gate's own function rather than a copy of it.
    """
    assert gen._check_version_ranges(gen.read_registry()) == []


@pytest.mark.parametrize("status", ["open", "partially_resolved", "wont_fix",
                                    "probably fine tbh"])
def test_a_closed_range_is_refused_for_every_unresolved_status(status):
    """The shape MADD-ANO-016 shipped in, for every reachable status."""
    registry = {"maddening_version": "0.4.0.dev0", "anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": status,
        "affected_versions": ">=0.1.0, <0.4.0",
    }]}
    errors = gen._check_version_ranges(registry)
    assert len(errors) == 1 and "MADD-ANO-999" in errors[0], errors


@pytest.mark.parametrize("status", ["resolved", "duplicate"])
def test_a_closed_range_is_allowed_once_the_defect_is_gone(status):
    registry = {"maddening_version": "0.4.0.dev0", "anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": status,
        "affected_versions": ">=0.3.0, <0.4.0",
    }]}
    assert gen._check_version_ranges(registry) == []


def test_an_open_range_is_refused_once_the_defect_is_resolved():
    """The shape MADD-ANO-006 shipped in: resolved in 0.4.0, `>=0.1.0`."""
    registry = {"maddening_version": "0.4.0.dev0", "anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": "resolved",
        "resolution_version": "0.4.0",
        "affected_versions": ">=0.1.0",
    }]}
    errors = gen._check_version_ranges(registry)
    assert errors and all("MADD-ANO-999" in e for e in errors), errors


@pytest.mark.parametrize("registry", [
    {"maddening_version": "0.4.0.dev0", "anomalies": [
        {"anomaly_id": "MADD-ANO-001", "resolution_status": "resolved",
         "affected_versions": "banana"}]},
    {"maddening_version": "0.4.0.dev0", "anomalies": []},
    {"anomalies": [{"anomaly_id": "MADD-ANO-001",
                    "resolution_status": "open",
                    "affected_versions": ">=0.1.0"}]},
])
def test_the_generator_and_the_registry_gate_run_one_rule(registry):
    """Two copies of this rule is how it came to be a prefix test in one
    place and absent from the other.  Garbage, an empty registry and a
    registry with no version must fail both, with the same messages."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "_range_gate", REPO_ROOT / "scripts" / "check_anomalies.py")
    gate = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gate)
    errors = gen._check_version_ranges(registry)
    assert errors, "the generator's range check passed a registry it must refuse"
    assert errors == gate.version_range_errors(registry)


@pytest.mark.parametrize(
    "version, expected",
    [
        ("0.4.0.dev0", True),
        ("1.0.0rc1", True),
        ("0.5.0a2", True),
        ("0.3.1", False),
        ("1.0.0", False),
    ],
)
def test_prerelease_detection_decides_whether_a_release_date_exists(
    version, expected
):
    assert gen.is_prerelease(version) is expected


class TestDriftIsClassified:
    """``describe_drift`` must distinguish the two opposite remedies.

    The generator's error message is read as an instruction, and for one of
    the two kinds of drift the old instruction -- regenerate and commit --
    completed the defect rather than fixing it.
    """

    _ROWS = "| MADD-ANO-001 | a |\n| MADD-ANO-002 | b |\n| MADD-ANO-003 | c |\n"

    @staticmethod
    def _explanation(message: str) -> str:
        """The classification, without the unified diff appended after it.

        The diff repeats every changed line, so an assertion against the
        whole message passes on the diff alone -- which is how a mutation
        that stopped the classifier naming the IDs it would remove went
        undetected by the first version of this test.
        """
        return message.split("--- ", 1)[0]

    def test_a_row_the_source_stopped_producing_is_not_a_regenerate(self):
        generated = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        explanation = self._explanation(
            gen.describe_drift("doc.md", self._ROWS, generated)
        )
        assert "DO NOT regenerate yet" in explanation
        assert "1 line(s) only in the COMMITTED file" in explanation

    def test_the_explanation_names_the_evidence_ids_it_would_remove(self):
        """Not the diff below it: the sentence a reader acts on."""
        generated = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        explanation = self._explanation(
            gen.describe_drift("doc.md", self._ROWS, generated)
        )
        assert "MADD-ANO-002" in explanation
        assert "MADD-ANO-001" not in explanation

    def test_a_row_the_document_is_missing_is_a_regenerate(self):
        committed = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        message = self._explanation(
            gen.describe_drift("doc.md", committed, self._ROWS)
        )
        assert "DO NOT regenerate yet" not in message
        assert "generate_soup_tables.py` and commit" in message
        assert "1 line(s) only in the GENERATED file" in message

    def test_a_changed_cell_reads_differently_from_a_removed_row(self):
        changed = self._ROWS.replace("| MADD-ANO-002 | b |", "| MADD-ANO-002 | B |")
        message = self._explanation(
            gen.describe_drift("doc.md", self._ROWS, changed)
        )
        assert "1 line(s) changed in place" in message
        assert "DO NOT regenerate yet" not in message

        removed = gen.describe_drift(
            "doc.md", self._ROWS,
            self._ROWS.replace("| MADD-ANO-002 | b |\n", ""),
        )
        assert message != removed

    @staticmethod
    def _opcodes(committed: str, generated: str) -> set:
        """Which ``difflib`` opcodes a fixture actually produces.

        Asserted in the tests below because the classifier reads those
        opcodes, so a fixture that cannot produce the opcode a defect
        lives in cannot see the defect however it is worded.  That is
        what happened here: ``test_a_mixed_drift_leads_with_the_dangerous_half``
        was written for exactly the missed case and keeps an anchor
        after the deleted row, so it only ever emitted ``delete`` +
        ``insert`` and never the ``replace`` the bug was in.
        """
        return {tag for tag, *_ in difflib.SequenceMatcher(
            None, committed.splitlines(keepends=True),
            generated.splitlines(keepends=True), autojunk=False).get_opcodes()}

    def test_a_mixed_drift_leads_with_the_dangerous_half(self):
        """One row lost and one row gained is still a potential deletion."""
        generated = (
            "| MADD-ANO-001 | a |\n| MADD-ANO-003 | c |\n| MADD-ANO-004 | d |\n"
        )
        # `003` survives unchanged directly after the deleted row, so this
        # shape is `delete` + `insert`.  It does NOT cover `replace`; the
        # test below does.
        assert self._opcodes(self._ROWS, generated) == {"equal", "delete", "insert"}
        message = self._explanation(
            gen.describe_drift("doc.md", self._ROWS, generated)
        )
        assert "DO NOT regenerate yet" in message
        assert "MADD-ANO-002" in message

    def test_a_row_deleted_next_to_an_edited_row_is_still_a_deletion(self):
        """The shape with no anchor after the deletion: one `replace`.

        Deleting ``MADD-ANO-012`` from ``known_anomalies.yaml`` and
        rewording the next anomaly's title is one change, and it is the
        shape of every "re-derive the registry" commit in this release.
        ``SequenceMatcher`` folds the two into a single ``replace``,
        whose old lines the classifier filed under "changed in place" --
        so it reported *0 lines only in the COMMITTED file* and printed
        the regenerate-and-commit instruction it exists to suppress,
        with the lost row visible in the diff underneath.
        """
        generated = (
            "| MADD-ANO-001 | a |\n| MADD-ANO-003 | c, reworded |\n"
        )
        assert self._opcodes(self._ROWS, generated) == {"equal", "replace"}, (
            "this fixture must produce a `replace` opcode or it cannot "
            "express the defect it is written for"
        )
        message = self._explanation(
            gen.describe_drift("doc.md", self._ROWS, generated)
        )
        assert "DO NOT regenerate yet" in message
        assert "MADD-ANO-002" in message
        # The count has to move with the verdict: a headline of "0 line(s)
        # only in the COMMITTED file" above a "DO NOT regenerate" would
        # read as a bug in the gate rather than a lost row.
        assert "1 line(s) only in the COMMITTED file" in message
        # The row that was only reworded is still reported as such.
        assert "1 line(s) changed in place" in message
        assert "MADD-ANO-003" not in message

    def test_an_id_lost_from_a_prose_line_is_named_too(self):
        """Not only table rows.

        The generated section ends with a sentence that counts the
        registered anomalies, and an ID can be mentioned in prose.  The
        classifier reads evidence IDs, not table syntax, so assert that
        directly rather than leaving it to the row tests -- the naming is
        what a maintainer acts on.
        """
        committed = (
            "| MADD-ANO-001 | a |\n"
            "*2 anomalies registered; MADD-ANO-002 is the open one.*\n"
        )
        generated = "| MADD-ANO-001 | a |\n*1 anomaly registered.*\n"
        message = self._explanation(
            gen.describe_drift("doc.md", committed, generated)
        )
        assert "DO NOT regenerate yet" in message
        assert "MADD-ANO-002" in message

    def test_an_edit_that_loses_no_row_is_still_a_plain_regenerate(self):
        """The fix must not turn every `replace` into a refusal.

        Two rows reworded in one block is a single `replace` with nothing
        lost; the remedy there really is to regenerate and commit.
        """
        generated = (
            "| MADD-ANO-001 | a |\n| MADD-ANO-002 | B |\n| MADD-ANO-003 | C |\n"
        )
        assert self._opcodes(self._ROWS, generated) == {"equal", "replace"}
        message = self._explanation(
            gen.describe_drift("doc.md", self._ROWS, generated)
        )
        assert "DO NOT regenerate yet" not in message
        assert "generate_soup_tables.py` and commit" in message
        assert "0 line(s) only in the COMMITTED file" in message
        assert "2 line(s) changed in place" in message

    def test_the_unified_diff_is_still_printed(self):
        generated = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        message = gen.describe_drift("doc.md", self._ROWS, generated)
        assert "doc.md (committed)" in message
        assert "-| MADD-ANO-002 | b |" in message


# ---------------------------------------------------------------------------
# MADD-ANO-001: the resolution is a dependency floor, so the floor is the
# evidence
# ---------------------------------------------------------------------------
# MADD-ANO-001 (LBM GPU segfault on CUDA 12.2 + jaxlib 0.5.1) is recorded
# `resolved` in 0.4.0 "by the dependency floor moving past the affected jaxlib
# rather than by any change to MADDENING's own code".  Nothing pinned that
# floor.  Restoring `jax>=0.4,<0.6` to pyproject.toml — which readmits the
# exact jaxlib the anomaly names — left `scripts/check_anomalies.py` printing
# OK and every compliance test passing but one: the generated-table equality
# gate, whose own message says to regenerate and commit, which would have
# rewritten §1 of soup_package.md around the regression and turned everything
# green again (measured 2026-09-20: 1 failed, 253 passed).
#
# So the resolution had no verification entry that could fail, which for an
# anomaly whose fix IS a version range is the whole of the evidence.  This is
# that entry.  It is deliberately about the *declared* range and not the
# installed version: what a user of 0.4.0 can install is what the anomaly
# claims, and CI's own pin is a single point inside the range.
_ANO_001_AFFECTED_JAXLIB = (0, 5, 1)


def _floor_of(requirement: str) -> tuple:
    """The ``>=`` floor of a PEP 508 requirement, as a version tuple."""
    _, _, rest = requirement.partition(">=")
    assert rest, f"{requirement!r} declares no >= floor"
    floor = rest.split(",")[0].strip()
    return tuple(int(part) for part in floor.split(".") if part.isdigit())


def test_the_dependency_floor_still_excludes_the_jaxlib_madd_ano_001_names():
    """Lowering the jax/jaxlib floor back over jaxlib 0.5.1 fails here.

    MADD-ANO-001's `resolution_status: resolved` rests on this and on
    nothing else in the tree.
    """
    pyproject = gen.read_pyproject()
    project = pyproject["project"]
    requirements = list(project["dependencies"])
    for extra in ("cuda12", "tpu"):
        requirements += list(project["optional-dependencies"].get(extra, []))

    checked = []
    for requirement in requirements:
        name = requirement.split(">=")[0].split("[")[0].strip()
        if name not in ("jax", "jaxlib"):
            continue
        checked.append(requirement)
        assert _floor_of(requirement) > _ANO_001_AFFECTED_JAXLIB, (
            f"{requirement!r} admits jaxlib "
            f"{'.'.join(str(n) for n in _ANO_001_AFFECTED_JAXLIB)}, the "
            f"version MADD-ANO-001 records as segfaulting the LBM GPU path.  "
            f"That anomaly is marked `resolved` solely because the floor "
            f"moved past it; lowering the floor reopens it, so either raise "
            f"the floor again or reopen MADD-ANO-001 in "
            f"docs/validation/known_anomalies.yaml."
        )

    assert len(checked) >= 4, (
        f"expected jax and jaxlib pins in [project.dependencies] and in the "
        f"cuda12 and tpu extras; found only {checked}.  An assertion that "
        f"iterates over nothing passes trivially — if a pin moved, point this "
        f"test at where it went."
    )


def test_madd_ano_001_is_recorded_resolved_by_that_floor():
    """The pin above is only evidence while the entry rests on it.

    If MADD-ANO-001 is ever reopened, or its resolution is re-attributed
    to a code change, this test's sibling stops being its verification
    and the registry should say so.
    """
    entry = next(
        a for a in gen.read_registry()["anomalies"]
        if a["anomaly_id"] == "MADD-ANO-001"
    )
    assert entry["resolution_status"] == "resolved"
    assert "0.5.1" in entry["description"], (
        "MADD-ANO-001 no longer names the affected jaxlib; "
        "_ANO_001_AFFECTED_JAXLIB above is stale"
    )


# ---------------------------------------------------------------------------
# The §3 headline counts reachable defects, not unclosed tickets
# ---------------------------------------------------------------------------
def test_the_anomaly_headline_counts_every_reachable_defect():
    """`partially_resolved` with a live residual risk is still reachable.

    The headline used to read "15 anomalies registered, 6 open", counting
    only `resolution_status == "open"` — while MADD-ANO-005 falls back to
    the pre-0.4.0 residual test on a reachable path and MADD-ANO-014's own
    residual risk says the degraded path "is still the default and still
    silent".  Eight defects were reachable and the document said six, in
    the direction that understates.

    The predicate is the registry gate's own (`check_anomalies`'s
    `UNREACHABLE_STATUSES`), so the headline and the version-range rule
    cannot drift apart.
    """
    registry = gen.read_registry()
    reachable = [
        a["anomaly_id"] for a in registry["anomalies"]
        if a.get("resolution_status") not in gen._UNREACHABLE_STATUSES
    ]
    assert reachable, "no reachable anomalies — the predicate matched nothing"

    rendered = gen.render_known_anomalies(registry)
    assert f"{len(reachable)} have a defect reachable in this version" in rendered, (
        f"the §3 headline does not report the {len(reachable)} reachable "
        f"defects {sorted(reachable)}:\n{rendered.splitlines()[-1]}"
    )


def test_a_partially_resolved_anomaly_is_counted_as_reachable():
    """The distinction the headline exists to make, pinned directly.

    Without this, flipping the headline back to `== "open"` still passes
    the test above on any registry that happens to hold no
    `partially_resolved` entry.
    """
    registry = {"anomalies": [
        {"anomaly_id": "MADD-ANO-001", "resolution_status": "open"},
        {"anomaly_id": "MADD-ANO-002",
         "resolution_status": "partially_resolved"},
        {"anomaly_id": "MADD-ANO-003", "resolution_status": "resolved"},
        {"anomaly_id": "MADD-ANO-004", "resolution_status": "wont_fix"},
        {"anomaly_id": "MADD-ANO-005", "resolution_status": "duplicate"},
    ]}
    rendered = gen.render_known_anomalies(registry)
    assert "3 have a defect reachable in this version" in rendered, rendered
    # Each reachable status is named with its own count.  This used to read
    # "2 `partially_resolved`": everything reachable that was not `open`
    # was labelled partially resolved, `wont_fix` included.
    assert "1 `open`" in rendered, rendered
    assert "1 `partially_resolved`" in rendered, rendered
    assert "1 `wont_fix`" in rendered, rendered


class TestTheCiDerivedRowsFollowTheMatrix:
    """The Python and JAX evidence rows must move when CI's matrix moves.

    Both rows say "verified on X" next to a permitted range, and the
    whole point of generating them is that X is read from
    ``.github/workflows/ci.yml`` rather than retyped.  A reader of the
    SOUP package cannot tell a row that tracks the matrix from one that
    is merely a plausible constant, so the tracking is pinned here.

    The failure mode these guard is specific and has happened to the
    JAX pin twice in shape: the pin is found by a regex over the
    workflow text, so the day the lanes install
    ``jax==${{ matrix.jax-version }}`` instead of a literal, the regex
    matches nothing.  Without a fail-closed path that reads "the
    declared range" rather than "what ran" -- which is the one
    substitution an IEC 62304 evidence table must never make.

    ``gen.CI_WORKFLOW`` is repointed at a temporary file, so none of
    this reads or writes the committed workflow.
    """

    @staticmethod
    def _ci(monkeypatch, tmp_path, text: str) -> dict:
        path = tmp_path / "ci.yml"
        path.write_text(text)
        monkeypatch.setattr(gen, "CI_WORKFLOW", path)
        return gen.read_ci()

    _MATRIX = """\
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.14"]
        jax-version: ["0.10.2", "0.11.2"]
    steps:
      - run: pip install "jax==${{ matrix.jax-version }}"
  compliance:
    runs-on: ubuntu-latest
    steps:
      - run: pip install "jax==0.10.2"
"""

    def test_both_axes_of_the_matrix_reach_the_rows(self, monkeypatch, tmp_path):
        ci = self._ci(monkeypatch, tmp_path, self._MATRIX)
        assert ci["pythons"] == ["3.12", "3.14"]
        # The literal pin in `compliance` and the axis the test lanes
        # install from are both points CI ran.  The regex alone sees
        # only the first.
        assert ci["jax_pins"] == ["0.10.2", "0.11.2"]
        assert "3.12, 3.14" in gen.verified_pythons(ci)
        assert "0.10.2, 0.11.2" in gen.verified_jax(ci)

    def test_the_include_form_of_a_matrix_is_read_too(self, monkeypatch, tmp_path):
        ci = self._ci(monkeypatch, tmp_path, """\
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.12"
            jax-version: "0.10.2"
          - python-version: "3.13"
            jax-version: "0.11.2"
""")
        assert ci["pythons"] == ["3.12", "3.13"]
        assert ci["jax_pins"] == ["0.10.2", "0.11.2"]

    def test_a_python_matrix_that_cannot_be_read_says_unknown(
        self, monkeypatch, tmp_path,
    ):
        """Never an empty string beside the word "verified"."""
        ci = self._ci(monkeypatch, tmp_path, """\
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install "jax==0.10.2"
""")
        assert ci["pythons"] == []
        row = gen.verified_pythons(ci)
        assert "**unknown**" in row, row
        assert "python-version" in row, row
        assert gen.ci_pythons(ci).startswith("**unknown**")

    def test_a_workflow_with_no_jax_pin_says_unknown_not_the_range(
        self, monkeypatch, tmp_path,
    ):
        """The substitution a SOUP document must never make."""
        ci = self._ci(monkeypatch, tmp_path, """\
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - run: pip install jax
""")
        assert ci["jax_pins"] == []
        row = gen.verified_jax(ci)
        assert "**verified point unknown**" in row, row
        evidence = gen.jax_evidence(ci, "jax>=0.10,<0.13")
        assert "**unknown**" in evidence, evidence
        assert "is not evidence" in evidence, evidence

    def test_the_jax_evidence_row_counts_the_pins_it_names(
        self, monkeypatch, tmp_path,
    ):
        """Two pins must not be described as "the only version"."""
        two = gen.jax_evidence({"jax_pins": ["0.10.2", "0.11.2"]}, "jax>=0.10,<0.13")
        assert "the 2 versions CI installs" in two, two
        assert "the only version" not in two, two
        one = gen.jax_evidence({"jax_pins": ["0.10.2"]}, "jax>=0.10,<0.13")
        assert "the only version CI installs" in one, one

    def test_a_deleted_job_or_strategy_degrades_instead_of_raising(
        self, monkeypatch, tmp_path,
    ):
        """A traceback is neither the answer nor the honest unknown."""
        for text in ("jobs:\n  test:\n",
                     "jobs:\n  test:\n    strategy:\n",
                     "jobs:\n",
                     "{}\n"):
            ci = self._ci(monkeypatch, tmp_path, text)
            assert ci["pythons"] == []
            assert "**unknown**" in gen.verified_pythons(ci)
