"""The committed SBOMs must describe the package ``pyproject.toml`` declares.

``docs/validation/sbom/`` holds one CycloneDX SBOM per covered install,
generated by ``scripts/generate_sbom.py`` from a clean install of the
wheel (network access, uv).  ``scripts/check_sbom.py`` compares them with
``pyproject.toml`` and the SOUP package offline, and this module runs it on
the committed files, so a dependency change or a version bump that is not
followed by a regeneration fails in CI's ``pytest tests/compliance/`` step.

Most of the module is the other direction: each defect the check exists
to catch is planted in a small fixture SBOM, and the check has to name it.
The fixtures are re-sealed after each mutation (their serial recomputed),
so it is the targeted rule that fires and not only the hand-edit guard;
that guard has tests of its own.  The generator's pure half
(``finalise``, ``installed_mismatch``) is tested the same way, with no
network.
"""

from __future__ import annotations

import copy
import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = REPO_ROOT / "scripts"

sys.path.insert(0, str(SCRIPTS))

import check_sbom  # noqa: E402
import generate_sbom  # noqa: E402

VERSION = "9.9.9"
ENV = {
    "implementation_name": "cpython",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_system": "Linux",
    "python_full_version": "3.12.3",
    "python_version": "3.12",
    "sys_platform": "linux",
}
PYPROJECT = {
    "project": {
        "name": "maddening",
        "version": VERSION,
        "license": "LGPL-3.0-or-later",
        "dependencies": ["jax>=0.10,<0.13", "numpy>=1.24", "pyyaml>=6.0"],
        "optional-dependencies": {
            "net": ["pyzmq>=25.0"],
            "bundle": ["maddening[net]", "rich>=12.0"],
            "gpu": ["nvlib>=1.0; sys_platform == 'linux'"],
        },
    }
}
SOUP_ITEMS = ["jax>=0.10,<0.13", "numpy>=1.24", "pyyaml>=6.0"]
CORE = {"jax": "0.11.2", "jaxlib": "0.11.2", "numpy": "2.5.3", "PyYAML": "6.0.3"}


def _ref(name: str, version: str) -> str:
    return f"{name}=={version}"


def make_sbom(install: str = "core", components: dict[str, str] | None = None,
              *, env: dict[str, str] | None = None, version: str = VERSION,
              pyproject: dict = PYPROJECT) -> dict:
    """A small SBOM shaped like ``generate_sbom.py``'s output, sealed."""
    components = dict(CORE if components is None else components)
    comps = [{"bom-ref": _ref(n, v), "name": n, "version": v, "type": "library",
              "purl": f"pkg:pypi/{n.lower()}@{v}",
              "licenses": [{"license": {"id": "MIT"}}]}
             for n, v in components.items()]
    by_key = {check_sbom.canonicalize_name(n): _ref(n, v) for n, v in components.items()}
    edges = []
    try:
        declared = check_sbom.declared_requirements(pyproject, install)
    except KeyError:                     # an install pyproject does not declare
        declared = []
    for req in declared:
        if req.marker is not None and not req.marker.evaluate({**(env or ENV), "extra": ""}):
            continue
        key = check_sbom.canonicalize_name(req.name)
        if key in by_key:
            edges.append(by_key[key])
    root_ref = f"maddening=={version}"
    deps = [{"ref": root_ref, "dependsOn": edges}]
    if "jax" in components and "jaxlib" in components:
        deps.append({"ref": by_key["jax"], "dependsOn": [by_key["jaxlib"]]})
    for n, v in components.items():
        if n != "jax":
            deps.append({"ref": _ref(n, v)})
    props = [{"name": check_sbom.PROP_INSTALL, "value": install},
             {"name": check_sbom.PROP_EXCLUDE_NEWER, "value": "2026-09-25T00:00:00Z"}]
    props += [{"name": check_sbom.PROP_MARKER + k, "value": v}
              for k, v in (ENV if env is None else env).items()]
    sbom = {
        "bomFormat": "CycloneDX", "specVersion": "1.6", "version": 1,
        "metadata": {
            "timestamp": "2026-09-25T00:00:00Z",
            "component": {"bom-ref": root_ref, "name": "maddening", "version": version,
                          "type": "library", "purl": f"pkg:pypi/maddening@{version}",
                          "licenses": [{"license": {"id": "LGPL-3.0-or-later"}}]},
            "properties": props,
        },
        "components": comps,
        "dependencies": deps,
    }
    return check_sbom.seal(sbom)


def errors_of(sbom: dict, install: str = "core", soup=SOUP_ITEMS,
              pyproject: dict = PYPROJECT) -> list[str]:
    return check_sbom.check_sbom(sbom, pyproject=pyproject, install=install,
                                 soup_requirements=soup)


def mutate(sbom: dict, fn) -> dict:
    """Apply ``fn`` to a copy and re-seal it, as a regeneration would."""
    out = copy.deepcopy(sbom)
    fn(out)
    return check_sbom.seal(out)


def component(sbom: dict, name: str) -> dict:
    return next(c for c in sbom["components"] if c["name"] == name)


def _has(errors: list[str], *fragments: str) -> bool:
    return any(all(f in e for f in fragments) for e in errors)


# ---------------------------------------------------------------------------
# The committed files
# ---------------------------------------------------------------------------


def test_the_committed_sboms_match_pyproject_and_the_soup_package():
    """The gate itself, on the repository: a stale SBOM fails here."""
    errors, sboms = check_sbom.check_directory(
        check_sbom.SBOM_DIR, pyproject=check_sbom.load_pyproject(),
        soup_text=check_sbom.SOUP_PACKAGE.read_text(encoding="utf-8"))
    assert not errors, (
        "the committed SBOMs disagree with their sources; regenerate them with "
        "`python scripts/generate_sbom.py` (network, uv) and commit the result:\n"
        + "\n".join(errors))
    assert len(sboms) == len(check_sbom.SBOM_INSTALLS)


def test_the_check_script_passes_on_the_repository_as_ci_runs_it():
    result = subprocess.run([sys.executable, str(SCRIPTS / "check_sbom.py")],
                            capture_output=True, text=True, cwd=REPO_ROOT)
    assert result.returncode == 0, result.stderr
    assert result.stdout.startswith(f"OK: {len(check_sbom.SBOM_INSTALLS)} SBOMs")


def test_the_soup_items_read_are_exactly_the_base_dependencies():
    """The parser must find every item, or the SOUP rule checks a subset."""
    text = check_sbom.SOUP_PACKAGE.read_text(encoding="utf-8")
    assert check_sbom.soup_items(text) == check_sbom.load_pyproject()["project"]["dependencies"]


def test_every_committed_sbom_is_one_generation_of_its_content():
    """Sealed, in canonical order, and written in the on-disk form."""
    for path in sorted(check_sbom.SBOM_DIR.glob("*.cdx.json")):
        text = path.read_text(encoding="utf-8")
        sbom = json.loads(text)
        assert check_sbom.dumps(check_sbom.seal(sbom)) == text, path.name


# ---------------------------------------------------------------------------
# Mutants: each defect has to be named
# ---------------------------------------------------------------------------


def test_the_fixture_is_consistent():
    """Every mutant below is measured against a fixture that passes."""
    assert errors_of(make_sbom()) == []
    assert errors_of(make_sbom("net", {**CORE, "pyzmq": "27.2.0"}), "net") == []


def test_a_document_that_is_not_cyclonedx_is_named():
    def change(s):
        s["bomFormat"] = "SPDX"
        del s["specVersion"]
    errors = errors_of(mutate(make_sbom(), change))
    assert _has(errors, "bomFormat is 'SPDX'")
    assert _has(errors, "has no specVersion")


def test_a_dropped_direct_dependency_is_named():
    sbom = mutate(make_sbom(), lambda s: s["components"].remove(component(s, "numpy")))
    errors = errors_of(sbom)
    assert _has(errors, "direct dependency numpy>=1.24", "missing from the SBOM")
    assert _has(errors, "SOUP item numpy", "not in the SBOM")


def test_a_version_outside_the_declared_range_is_named():
    sbom = mutate(make_sbom(), lambda s: component(s, "numpy").update(
        version="1.20.0", purl="pkg:pypi/numpy@1.20.0"))
    errors = errors_of(sbom)
    assert _has(errors, "direct dependency numpy is at 1.20.0", "numpy>=1.24")
    assert _has(errors, "SOUP item numpy is at 1.20.0")


def test_a_soup_item_absent_from_the_sbom_and_pyproject_is_named():
    errors = errors_of(make_sbom(), soup=SOUP_ITEMS + ["scipy>=1.0"])
    assert _has(errors, "SOUP item scipy listed in soup_package.md is not in the SBOM")
    assert _has(errors, "SOUP item scipy", "declares no base dependency")


def test_a_soup_item_pyproject_does_not_declare_is_named_even_when_installed():
    sbom = make_sbom(components={**CORE, "scipy": "1.18.1"})
    errors = errors_of(sbom, soup=SOUP_ITEMS + ["scipy>=1.0"])
    assert errors == [f"SBOM: SOUP item scipy is listed in soup_package.md, but "
                      f"pyproject.toml declares no base dependency of that name"]


def test_a_soup_item_is_held_to_the_pyproject_range_not_the_documents():
    """The SOUP row may say anything; pyproject's range is the one checked."""
    sbom = make_sbom(components={**CORE, "jax": "0.13.0"})
    errors = errors_of(sbom, soup=["jax>=0.1"] + SOUP_ITEMS[1:])
    assert _has(errors, "SOUP item jax is at 0.13.0", "jax<0.13,>=0.10")


def test_a_wrong_root_version_is_named():
    sbom = mutate(make_sbom(), lambda s: s["metadata"]["component"].update(version="0.3.1"))
    assert _has(errors_of(sbom), "root component is maddening 0.3.1", VERSION)


def test_a_wrong_root_purl_or_licence_is_named():
    def change(s):
        s["metadata"]["component"]["purl"] = "pkg:pypi/maddening@0.0.1"
        s["metadata"]["component"]["licenses"] = [{"license": {"id": "MIT"}}]
    errors = errors_of(mutate(make_sbom(), change))
    assert _has(errors, "root component purl")
    assert _has(errors, "root component licence", "LGPL-3.0-or-later")


def test_an_sbom_of_another_install_is_named():
    assert _has(errors_of(make_sbom(), install="net"), "records install 'core'",
                "expected 'net'")


def test_an_sbom_that_does_not_record_its_environment_is_refused():
    env = {k: v for k, v in ENV.items() if k != "python_full_version"}
    errors = errors_of(make_sbom(env=env))
    assert _has(errors, "does not record the environment",
                "maddening:sbom:marker:python_full_version")


@pytest.mark.parametrize("change, fragment", [
    (lambda c: c.pop("purl"), "has no purl"),
    (lambda c: c.update(purl="pkg:pypi/numpie@2.5.3"), "names a different package"),
    (lambda c: c.update(purl="pkg:pypi/numpy@2.5.2"), "names version '2.5.2'"),
    (lambda c: c.update(purl="pkg:npm/numpy@2.5.3"), "is not a pkg:pypi purl"),
    (lambda c: c.pop("version"), "has no version"),
])
def test_a_bad_component_purl_or_version_is_named(change, fragment):
    sbom = mutate(make_sbom(), lambda s: change(component(s, "numpy")))
    assert _has(errors_of(sbom), "component numpy", fragment)


def test_a_package_listed_twice_is_named():
    def dup(s):
        extra = dict(component(s, "numpy"), version="2.5.4", purl="pkg:pypi/numpy@2.5.4")
        extra["bom-ref"] = "numpy==2.5.4"
        s["components"].append(extra)
    assert _has(errors_of(mutate(make_sbom(), dup)), "component numpy appears twice")


def test_maddening_listed_as_a_component_is_named():
    def add(s):
        s["components"].append({"bom-ref": "m", "name": "maddening", "version": VERSION,
                                "purl": f"pkg:pypi/maddening@{VERSION}"})
    assert _has(errors_of(mutate(make_sbom(), add)), "maddening is listed as a component")


def test_a_dangling_dependency_reference_is_named():
    sbom = mutate(make_sbom(), lambda s: s["dependencies"].append(
        {"ref": "numpy==2.5.3x", "dependsOn": ["ghost==1"]}))
    errors = errors_of(sbom)
    assert _has(errors, "'numpy==2.5.3x' names no component")
    assert _has(errors, "depends on 'ghost==1'")


def test_a_missing_root_edge_is_named():
    def drop(s):
        root = next(d for d in s["dependencies"] if d["ref"] == f"maddening=={VERSION}")
        root["dependsOn"].remove("numpy==2.5.3")
    assert _has(errors_of(mutate(make_sbom(), drop)),
                "root component does not depend on 'numpy==2.5.3'")


def test_a_root_edge_to_an_undeclared_package_is_named():
    """What cyclonedx-py writes by itself: an unselected extra's package as direct."""
    def add(s):
        root = next(d for d in s["dependencies"] if d["ref"] == f"maddening=={VERSION}")
        root["dependsOn"].append("jaxlib==0.11.2")
    assert _has(errors_of(mutate(make_sbom(), add)),
                "root component depends on 'jaxlib==0.11.2'", "does not declare")


def test_a_hand_edited_sbom_is_refused():
    """Bumping a version in the JSON to satisfy the check is not a regeneration."""
    sbom = copy.deepcopy(make_sbom())
    component(sbom, "numpy")["version"] = "2.5.4"
    component(sbom, "numpy")["purl"] = "pkg:pypi/numpy@2.5.4"
    errors = errors_of(sbom)
    assert _has(errors, "serialNumber does not match the content")


def test_an_sbom_without_a_serial_is_refused():
    sbom = copy.deepcopy(make_sbom())
    del sbom["serialNumber"]
    assert _has(errors_of(sbom), "has no serialNumber")


def test_components_out_of_canonical_order_are_named():
    sbom = copy.deepcopy(make_sbom())
    sbom["components"].reverse()
    sbom["serialNumber"] = check_sbom.content_serial(sbom)
    assert errors_of(sbom) == ["SBOM: components are not in canonical order (by package "
                               "name, then version); regenerate it with "
                               "scripts/generate_sbom.py"]


def test_an_extras_direct_dependency_missing_from_its_sbom_is_named():
    errors = errors_of(make_sbom("net"), "net")
    assert _has(errors, "direct dependency pyzmq>=25.0", "[net]", "missing")


def test_an_extra_that_names_another_extra_needs_both():
    """``bundle`` = ``maddening[net]`` + rich: pyzmq is direct through the self-reference."""
    ok = make_sbom("bundle", {**CORE, "pyzmq": "27.2.0", "rich": "15.0.0"})
    assert errors_of(ok, "bundle") == []
    no_zmq = make_sbom("bundle", {**CORE, "rich": "15.0.0"})
    assert _has(errors_of(no_zmq, "bundle"), "direct dependency pyzmq>=25.0", "missing")


def test_two_extras_joined_by_a_plus_are_both_required():
    assert check_sbom.install_requirement("net+gpu") == "maddening[net,gpu]"
    sbom = make_sbom("net+gpu", {**CORE, "nvlib": "1.2"})
    assert _has(errors_of(sbom, "net+gpu"), "direct dependency pyzmq>=25.0", "missing")


def test_a_dependency_whose_marker_is_false_is_not_required():
    darwin = {**ENV, "sys_platform": "darwin", "platform_system": "Darwin"}
    assert errors_of(make_sbom("gpu", env=darwin), "gpu") == []
    assert _has(errors_of(make_sbom("gpu"), "gpu"), "direct dependency nvlib>=1.0", "missing")


def test_an_install_pyproject_does_not_declare_is_named():
    assert _has(errors_of(make_sbom("nosuch"), "nosuch"), "declares no extra 'nosuch'")


def test_a_prerelease_inside_the_range_is_admitted():
    """As ``pip check`` reads it: 0.12.0rc1 satisfies jax>=0.10,<0.13."""
    sbom = make_sbom(components={**CORE, "jax": "0.12.0rc1"})
    assert errors_of(sbom) == []


# ---------------------------------------------------------------------------
# The directory and the SOUP document
# ---------------------------------------------------------------------------


def _soup_text(installs=check_sbom.SBOM_INSTALLS, version=VERSION,
               row="jax>=0.10,<0.13, numpy>=1.24, pyyaml>=6.0") -> str:
    names = "\n".join(f"- `{check_sbom.sbom_filename(version, i)}`" for i in installs)
    return (
        "## 1. Software Identification\n\n"
        "<!-- BEGIN GENERATED: software-identification -- x -->\n"
        "| Field | Value |\n|---|---|\n"
        f"| Base Dependencies | {row} |\n"
        "<!-- END GENERATED: software-identification -->\n\n"
        f"## 6. SBOM\n\n{names}\n"
    )


def _pyproject_with_extras() -> dict:
    out = copy.deepcopy(PYPROJECT)
    extras = out["project"]["optional-dependencies"]
    extras.update({"server": ["pyzmq>=25.0"], "surrogates": ["optax>=0.1"],
                   "usd": ["usd-core>=21.8"]})
    return out


_EXTRA_COMPONENTS = {"core": {}, "server": {"pyzmq": "27.2.0"},
                     "surrogates": {"optax": "0.2.8"}, "usd": {"usd-core": "26.8"}}


def _write_dir(path: Path, pyproject: dict, installs=check_sbom.SBOM_INSTALLS,
               version=VERSION) -> None:
    path.mkdir(parents=True, exist_ok=True)
    for install in installs:
        sbom = make_sbom(install, {**CORE, **_EXTRA_COMPONENTS[install]},
                         version=version, pyproject=pyproject)
        (path / check_sbom.sbom_filename(version, install)).write_text(
            check_sbom.dumps(sbom), encoding="utf-8")


def test_a_consistent_directory_passes(tmp_path):
    pyproject = _pyproject_with_extras()
    _write_dir(tmp_path, pyproject)
    errors, sboms = check_sbom.check_directory(tmp_path, pyproject=pyproject,
                                               soup_text=_soup_text())
    assert errors == [] and len(sboms) == 4


def test_a_missing_sbom_for_a_covered_install_is_named(tmp_path):
    pyproject = _pyproject_with_extras()
    _write_dir(tmp_path, pyproject, installs=("core", "server", "usd"))
    errors, _ = check_sbom.check_directory(tmp_path, pyproject=pyproject,
                                           soup_text=_soup_text())
    assert _has(errors, f"maddening-{VERSION}-surrogates.cdx.json: missing",
                "generate_sbom.py")


def test_a_version_bump_without_regenerating_fails(tmp_path):
    """The release step the check enforces: new version, old files."""
    pyproject = _pyproject_with_extras()
    _write_dir(tmp_path, pyproject)
    bumped = copy.deepcopy(pyproject)
    bumped["project"]["version"] = "10.0.0"
    errors, _ = check_sbom.check_directory(tmp_path, pyproject=bumped,
                                           soup_text=_soup_text(version="10.0.0"))
    assert _has(errors, "maddening-10.0.0-core.cdx.json: missing")
    assert _has(errors, f"maddening-{VERSION}-core.cdx.json: unexpected SBOM",
                "a previous version's file")


def test_an_sbom_for_an_uncovered_install_is_named(tmp_path):
    pyproject = _pyproject_with_extras()
    _write_dir(tmp_path, pyproject)
    (tmp_path / f"maddening-{VERSION}-cuda12.cdx.json").write_text("{}")
    errors, _ = check_sbom.check_directory(tmp_path, pyproject=pyproject,
                                           soup_text=_soup_text())
    assert _has(errors, "cuda12.cdx.json: unexpected SBOM",
                "an install this check does not cover")


def test_a_soup_document_that_does_not_name_an_sbom_is_named(tmp_path):
    pyproject = _pyproject_with_extras()
    _write_dir(tmp_path, pyproject)
    errors, _ = check_sbom.check_directory(
        tmp_path, pyproject=pyproject,
        soup_text=_soup_text(installs=("core", "server", "surrogates")))
    assert errors == [f"soup_package.md does not name maddening-{VERSION}-usd.cdx.json, "
                      f"the usd SBOM; list it in §6"]


def test_a_soup_document_without_a_base_dependencies_row_fails_closed(tmp_path):
    pyproject = _pyproject_with_extras()
    _write_dir(tmp_path, pyproject)
    text = _soup_text().replace("Base Dependencies", "Dependencies")
    errors, _ = check_sbom.check_directory(tmp_path, pyproject=pyproject, soup_text=text)
    assert _has(errors, "no 'Base Dependencies' row")
    with pytest.raises(ValueError, match="empty"):
        check_sbom.soup_items(_soup_text(row=""))
    with pytest.raises(ValueError, match="no generated"):
        check_sbom.soup_items("no table here")


def test_a_specifier_with_a_spaced_comma_stays_one_soup_item():
    text = _soup_text(row="jax>=0.10, <0.13, numpy>=1.24")
    assert check_sbom.soup_items(text) == ["jax>=0.10,<0.13", "numpy>=1.24"]


def test_the_cli_names_a_planted_defect_and_exits_non_zero(tmp_path):
    pyproject = _pyproject_with_extras()
    sbom_dir = tmp_path / "sbom"
    _write_dir(sbom_dir, pyproject)
    path = sbom_dir / check_sbom.sbom_filename(VERSION, "server")
    planted = mutate(json.loads(path.read_text()),
                     lambda s: s["components"].remove(component(s, "pyzmq")))
    path.write_text(check_sbom.dumps(planted))
    toml = tmp_path / "pyproject.toml"
    extras = pyproject["project"]["optional-dependencies"]
    toml.write_text(
        "[project]\nname = \"maddening\"\n"
        f"version = \"{VERSION}\"\nlicense = \"LGPL-3.0-or-later\"\n"
        f"dependencies = {json.dumps(pyproject['project']['dependencies'])}\n"
        "[project.optional-dependencies]\n"
        + "".join(f"{k} = {json.dumps(v)}\n" for k, v in extras.items()))
    soup = tmp_path / "soup.md"
    soup.write_text(_soup_text())
    result = subprocess.run(
        [sys.executable, str(SCRIPTS / "check_sbom.py"), "--sbom-dir", str(sbom_dir),
         "--pyproject", str(toml), "--soup", str(soup)],
        capture_output=True, text=True)
    assert result.returncode == 1
    assert "server.cdx.json: direct dependency pyzmq>=25.0" in result.stderr
    assert "names no component" in result.stderr        # the edges left behind
    assert "FAILED: " in result.stderr


# ---------------------------------------------------------------------------
# Sealing and normalisation
# ---------------------------------------------------------------------------


def test_sealing_is_deterministic_and_idempotent():
    a = make_sbom()
    assert check_sbom.seal(a) == a
    shuffled = copy.deepcopy(a)
    shuffled["components"].reverse()
    shuffled["dependencies"].reverse()
    shuffled["metadata"]["properties"].reverse()
    assert check_sbom.dumps(check_sbom.seal(shuffled)) == check_sbom.dumps(a)


def test_the_serial_changes_with_the_content():
    a = make_sbom()
    b = mutate(a, lambda s: component(s, "numpy").update(version="2.5.4"))
    assert a["serialNumber"] != b["serialNumber"]
    assert a["serialNumber"].startswith("urn:uuid:")


def test_normalising_drops_exactly_the_date_dependent_fields():
    a = make_sbom()
    b = mutate(a, lambda s: (
        s["metadata"].update(timestamp="2027-01-01T00:00:00Z"),
        next(p for p in s["metadata"]["properties"]
             if p["name"] == check_sbom.PROP_EXCLUDE_NEWER).update(value="2027-01-01"),
    ))
    assert a != b
    na, nb = check_sbom.normalise(a), check_sbom.normalise(b)
    assert na == nb
    assert "serialNumber" not in na and "timestamp" not in na["metadata"]
    kept = {p["name"] for p in na["metadata"]["properties"]}
    assert check_sbom.PROP_INSTALL in kept and check_sbom.PROP_EXCLUDE_NEWER not in kept
    # A resolved-environment difference survives normalisation.
    c = mutate(a, lambda s: component(s, "numpy").update(version="2.5.4"))
    assert check_sbom.normalise(c) != na


def test_the_normalise_cli_prints_the_normalised_file(tmp_path):
    path = tmp_path / "x.cdx.json"
    path.write_text(check_sbom.dumps(make_sbom()))
    result = subprocess.run([sys.executable, str(SCRIPTS / "check_sbom.py"),
                             "--normalise", str(path)], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    assert json.loads(result.stdout) == check_sbom.normalise(make_sbom())


# ---------------------------------------------------------------------------
# The generator's pure half
# ---------------------------------------------------------------------------


def _raw(components: dict[str, str], root_edges: list[str], licences=True) -> dict:
    """The shape ``cyclonedx-py environment --pyproject`` writes."""
    comps = [{"bom-ref": _ref(n, v), "name": n, "version": v, "type": "library",
              "purl": f"pkg:pypi/{n.lower()}@{v}"} for n, v in components.items()]
    if licences:
        for c in comps:
            c["licenses"] = [{"license": {"acknowledgement": "declared", "id": "MIT"}}]
    return {
        "bomFormat": "CycloneDX", "specVersion": "1.6", "version": 1,
        "metadata": {
            "component": {"bom-ref": "root-component", "name": "maddening",
                          "version": VERSION, "type": "library",
                          "licenses": [{"license": {"id": "LGPL-3.0-or-later"}}]},
            "properties": [{"name": "cdx:reproducible", "value": "true"}],
        },
        "components": comps,
        "dependencies": [{"ref": "root-component", "dependsOn": root_edges}]
        + [{"ref": _ref(n, v)} for n, v in components.items()],
    }


def _probe(components: dict[str, str], license_fields=None) -> dict:
    return {"marker": dict(ENV), "platform": "linux-x86_64", "libc": "glibc 2.39",
            "distributions": [[n, v] for n, v in components.items()] + [["maddening", VERSION]],
            "license_fields": license_fields or {}}


def _finalise(raw, probe, install="core"):
    return generate_sbom.finalise(
        raw, pyproject=PYPROJECT, install=install, probe=probe,
        provenance={"exclude-newer": "2026-09-25T00:00:00Z"},
        timestamp="2026-09-25T00:00:00Z")


def test_finalise_replaces_cyclonedx_root_edges_with_the_declared_ones():
    """cyclonedx-py linked the root to jaxlib here, as it linked equinox for real."""
    comps = dict(CORE)
    raw = _raw(comps, [_ref(n, v) for n, v in comps.items()])
    sbom = _finalise(raw, _probe(comps))
    root = next(d for d in sbom["dependencies"] if d["ref"] == f"maddening=={VERSION}")
    assert root["dependsOn"] == ["PyYAML==6.0.3", "jax==0.11.2", "numpy==2.5.3"]
    assert sbom["metadata"]["component"]["purl"] == f"pkg:pypi/maddening@{VERSION}"
    assert not any(d["ref"] == "root-component" for d in sbom["dependencies"])
    assert errors_of(sbom) == []


def test_finalise_records_the_install_and_its_environment():
    sbom = _finalise(_raw(CORE, []), _probe(CORE))
    props = {p["name"]: p["value"] for p in sbom["metadata"]["properties"]}
    assert props[check_sbom.PROP_INSTALL] == "core"
    assert props[check_sbom.PROP + "platform"] == "linux-x86_64"
    assert props[check_sbom.PROP_MARKER + "python_full_version"] == "3.12.3"
    assert props["cdx:reproducible"] == "true"
    assert sbom["metadata"]["timestamp"] == "2026-09-25T00:00:00Z"


def test_finalise_refuses_an_environment_missing_a_declared_dependency():
    comps = {k: v for k, v in CORE.items() if k != "numpy"}
    with pytest.raises(ValueError, match="numpy>=1.24"):
        _finalise(_raw(comps, []), _probe(comps))


def test_finalise_carries_a_short_licence_field_cyclonedx_dropped():
    """usd-core declares ``License: LicenseRef-TOST-1.0``; cyclonedx-py gave it none."""
    comps = {**CORE, "usd-core": "26.8"}
    raw = _raw(comps, [])
    component(raw, "usd-core").pop("licenses")
    component(raw, "numpy").pop("licenses")
    sbom = _finalise(raw, _probe(comps, {"usd-core": "LicenseRef-TOST-1.0",
                                         "numpy": "Copyright ...\n\nlong text",
                                         "jax": "Apache-2.0-but-ignored"}))
    assert component(sbom, "usd-core")["licenses"] == [
        {"license": {"acknowledgement": "declared", "name": "LicenseRef-TOST-1.0"}}]
    assert "licenses" not in component(sbom, "numpy")        # licence text, not a name
    assert component(sbom, "jax")["licenses"][0]["license"]["id"] == "MIT"  # kept


def test_finalise_is_independent_of_the_order_cyclonedx_wrote():
    raw = _raw(CORE, [])
    flipped = copy.deepcopy(raw)
    flipped["components"].reverse()
    flipped["dependencies"].reverse()
    a, b = _finalise(raw, _probe(CORE)), _finalise(flipped, _probe(CORE))
    assert check_sbom.dumps(a) == check_sbom.dumps(b)


def test_installed_mismatch_catches_a_leaked_and_a_dropped_package():
    sbom = _finalise(_raw(CORE, []), _probe(CORE))
    assert generate_sbom.installed_mismatch(sbom, _probe(CORE)["distributions"]) == []
    leaked = _probe(CORE)["distributions"] + [["pip", "25.0"]]
    assert generate_sbom.installed_mismatch(sbom, leaked) == [
        "pip: installed 25.0, in the SBOM None"]
    dropped = [d for d in _probe(CORE)["distributions"] if d[0] != "numpy"]
    assert generate_sbom.installed_mismatch(sbom, dropped) == [
        "numpy: installed None, in the SBOM 2.5.3"]


def test_the_timestamp_is_the_cutoff_unless_source_date_epoch_is_set(monkeypatch):
    cutoff = generate_sbom._parse_cutoff("2026-09-25")
    monkeypatch.delenv("SOURCE_DATE_EPOCH", raising=False)
    assert generate_sbom._timestamp(cutoff) == "2026-09-25T00:00:00Z"
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "0")
    assert generate_sbom._timestamp(cutoff) == "1970-01-01T00:00:00Z"
    assert generate_sbom._parse_cutoff("2026-09-25T12:30:00+02:00").hour == 10
