"""The SOUP evidence set must match the sources it summarises.

``docs/validation/soup_package.md`` and
``docs/validation/framework_verification.md`` carry summary tables of
``known_anomalies.yaml``, the ``@verification_benchmark`` registry and
``pyproject.toml``.  They were hand-maintained and drifted: 2 of 5
anomalies, 1 of 4 registered benchmarks, 7 of 12 test packages, and a
version identification two to three releases behind the package.  For
IEC 62304 evidence, drift is itself the finding.

The tables are now generated by ``scripts/generate_soup_tables.py``.
This module runs that script's ``--check`` mode, so a stale table fails
in CI's existing ``pytest tests/compliance/`` step rather than shipping.

The checks could later fold into ``scripts/check_anomalies.py``, which
CI's ``compliance`` job already runs; they live here because that script
was being rewritten concurrently.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

os.environ.setdefault("JAX_PLATFORMS", "cpu")

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_soup_tables.py"

sys.path.insert(0, str(REPO_ROOT / "scripts"))

import generate_soup_tables as gen  # noqa: E402


def _run_check() -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ, "JAX_PLATFORMS": "cpu"},
    )


def test_the_committed_soup_tables_match_a_fresh_generation():
    """A table that has drifted from its source fails here, not in review.

    This message deliberately does *not* tell you to regenerate and commit.
    It used to, and the generator's own error said the same thing, so the
    instruction was the same whichever kind of drift had occurred.  When the
    committed document holds a row the source no longer produces -- an
    anomaly deleted from the registry, a benchmark ID overwritten by a
    duplicate decorator -- regenerating removes that row from the evidence
    set and turns every gate green.  The generator now classifies the drift;
    read what it says before running anything.
    """
    result = _run_check()
    assert result.returncode == 0, (
        "The SOUP evidence set does not match the sources it summarises.  "
        "The generator's report below says which KIND of difference it found "
        "— a row missing from the committed document is not the same "
        "defect as a row the source has stopped producing, and only the "
        "first is fixed by regenerating.\n\n"
        + result.stdout + result.stderr
    )


# ---------------------------------------------------------------------------
# Registry membership: the document -> registry direction
# ---------------------------------------------------------------------------
# Every other check in this file runs registry -> document.  Nothing ran the
# other way and nothing pinned either registry's size or ID set, so an entry
# could be deleted from the source and the evidence set regenerated around the
# hole: 188 compliance tests green, the anomaly gone from soup_package.md
# (audit_040_r2/gates, finding G5).  Both ID spaces are contiguous, which is
# what makes a committed high-water mark a complete pin.
#
# These constants fail on a deletion AND on an unannounced addition.  The
# second is deliberate: adding an anomaly or a benchmark is a considered act,
# and bumping the number here is part of it.
#
# RETIRING AN ID: never delete the entry and never reuse the number.  Put the
# ID in the matching ``_RETIRED_*`` frozenset below, with a comment saying
# what was retired and when.  The number stays spoken for, the high-water mark
# stays honest, and the retirement is a visible line in the diff instead of a
# gap nobody can account for.
_HIGHEST_ANOMALY_ID = 15
_RETIRED_ANOMALY_IDS: frozenset = frozenset()

_HIGHEST_BENCHMARK_ID = 13
_RETIRED_BENCHMARK_IDS: frozenset = frozenset()


def _expected_ids(prefix: str, highest: int, retired: frozenset) -> set:
    return {f"{prefix}{n:03d}" for n in range(1, highest + 1)} - set(retired)


def _membership_message(kind: str, missing: set, unexpected: set) -> str:
    parts = []
    if missing:
        parts.append(
            f"{kind} missing from the registry: {sorted(missing)}.  An entry "
            f"in the committed set is IEC 62304 evidence; restore it, or "
            f"record the retirement in the _RETIRED_* frozenset in "
            f"tests/compliance/test_soup_evidence.py rather than deleting it."
        )
    if unexpected:
        parts.append(
            f"{kind} in the registry but not in the committed set: "
            f"{sorted(unexpected)}.  Raise the high-water mark in "
            f"tests/compliance/test_soup_evidence.py in the same commit that "
            f"adds the entry."
        )
    return "  ".join(parts)


def test_the_anomaly_registry_holds_exactly_the_committed_id_set():
    """Deleting an anomaly must turn something red before the generator runs."""
    actual = {a["anomaly_id"] for a in gen.read_registry()["anomalies"]}
    expected = _expected_ids(
        "MADD-ANO-", _HIGHEST_ANOMALY_ID, _RETIRED_ANOMALY_IDS
    )
    assert actual == expected, _membership_message(
        "anomaly ID(s)", expected - actual, actual - expected
    )


def test_the_benchmark_registry_holds_exactly_the_committed_id_set():
    """The same pin for ``@verification_benchmark``.

    A duplicate ``benchmark_id`` now raises at import time, but this is the
    pin that does not depend on *how* an entry went missing: a decorator
    deleted, a module dropped from ``BENCHMARK_MODULES``, or a test file
    removed all land here.
    """
    actual = set(gen.load_benchmarks())
    expected = _expected_ids(
        "MADD-VER-", _HIGHEST_BENCHMARK_ID, _RETIRED_BENCHMARK_IDS
    )
    assert actual == expected, _membership_message(
        "benchmark ID(s)", expected - actual, actual - expected
    )


def test_a_retired_id_is_recorded_and_not_reused():
    """A retired ID stays retired: absent from the registry, inside the range.

    An ID outside the high-water mark in ``_RETIRED_*`` is a typo, and one
    still present in the registry means the retirement never happened.
    """
    for label, retired, highest, registry_ids in (
        ("anomaly", _RETIRED_ANOMALY_IDS, _HIGHEST_ANOMALY_ID,
         {a["anomaly_id"] for a in gen.read_registry()["anomalies"]}),
        ("benchmark", _RETIRED_BENCHMARK_IDS, _HIGHEST_BENCHMARK_ID,
         set(gen.load_benchmarks())),
    ):
        for rid in retired:
            number = int(rid.rsplit("-", 1)[1])
            assert 1 <= number <= highest, (
                f"retired {label} ID {rid} is outside 1..{highest}"
            )
            assert rid not in registry_ids, (
                f"{rid} is recorded as a retired {label} ID but is still in "
                f"the registry"
            )


def test_every_anomaly_in_the_registry_reaches_the_summary_table():
    """The §3 table is complete, whatever the generator did to format it."""
    registry = gen.read_registry()
    rendered = gen.SOUP_PACKAGE.read_text()
    for anomaly in registry["anomalies"]:
        assert anomaly["anomaly_id"] in rendered, (
            f"{anomaly['anomaly_id']} is in known_anomalies.yaml but not in "
            f"soup_package.md"
        )


def test_every_registered_benchmark_reaches_the_verification_index():
    """The verification index is complete against the live registry."""
    benchmarks = gen.load_benchmarks()
    assert benchmarks, "no MADD-VER benchmarks registered — check the imports"
    rendered = gen.FRAMEWORK_VERIFICATION.read_text()
    for benchmark_id in benchmarks:
        assert benchmark_id in rendered, (
            f"{benchmark_id} is registered but missing from "
            f"framework_verification.md"
        )


def test_a_test_module_that_registers_a_benchmark_is_wired_into_the_index():
    """A new benchmark cannot register without joining BENCHMARK_MODULES.

    Without this the index stays green while going incomplete, which is
    how MADD-VER-002/003/004 ended up unlisted.
    """
    assert gen._check_benchmark_modules_are_complete() == []


def test_every_test_package_is_described_in_the_organization_table():
    assert gen._check_test_directories_are_described(gen.test_packages()) == []


def test_the_version_is_identified_the_same_way_everywhere():
    """pyproject is authoritative; the registry and CITATION.cff follow it."""
    assert gen._check_versions(
        gen.read_pyproject(), gen.read_registry(), gen.read_citation()
    ) == []


def test_an_unresolved_anomaly_does_not_record_a_closed_version_range():
    """A reachable defect and a closed version range cannot both be true.

    MADD-ANO-001 and MADD-ANO-002 sat in exactly that state for three
    releases: still reproducible, but recorded as affecting only the
    version they were first seen in.  MADD-ANO-005 was the worse case --
    `partially_resolved` with `<=0.3.0`, asserting 0.4.0 is clean while
    its own `residual_risk` describes the path on which the pre-0.4.0
    behaviour returns.  Only `resolved` and `duplicate` may close a
    range; anything else, including a status nobody has enumerated, may
    not.
    """
    assert gen._check_unresolved_anomalies_are_open_ended(
        gen.read_registry()
    ) == []


@pytest.mark.parametrize("status", ["open", "partially_resolved", "wont_fix",
                                    "probably fine tbh"])
def test_a_closed_range_is_refused_for_every_unresolved_status(status):
    registry = {"anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": status,
        "affected_versions": "0.1.0",
    }]}
    errors = gen._check_unresolved_anomalies_are_open_ended(registry)
    assert len(errors) == 1 and "MADD-ANO-999" in errors[0]


@pytest.mark.parametrize("status", ["resolved", "duplicate"])
def test_a_closed_range_is_allowed_once_the_defect_is_gone(status):
    registry = {"anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": status,
        "affected_versions": "0.3.0, 0.3.1",
    }]}
    assert gen._check_unresolved_anomalies_are_open_ended(registry) == []


@pytest.mark.parametrize(
    "version, expected",
    [
        ("0.4.0.dev0", True),
        ("1.0.0rc1", True),
        ("0.5.0a2", True),
        ("0.3.1", False),
        ("1.0.0", False),
    ],
)
def test_prerelease_detection_decides_whether_a_release_date_exists(
    version, expected
):
    assert gen.is_prerelease(version) is expected


class TestDriftIsClassified:
    """``describe_drift`` must distinguish the two opposite remedies.

    The generator's error message is read as an instruction, and for one of
    the two kinds of drift the old instruction -- regenerate and commit --
    completed the defect rather than fixing it.
    """

    _ROWS = "| MADD-ANO-001 | a |\n| MADD-ANO-002 | b |\n| MADD-ANO-003 | c |\n"

    def test_a_row_the_source_stopped_producing_is_not_a_regenerate(self):
        generated = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        message = gen.describe_drift("doc.md", self._ROWS, generated)
        assert "DO NOT regenerate yet" in message
        assert "MADD-ANO-002" in message
        assert "1 line(s) only in the COMMITTED file" in message

    def test_a_row_the_document_is_missing_is_a_regenerate(self):
        committed = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        message = gen.describe_drift("doc.md", committed, self._ROWS)
        assert "DO NOT regenerate yet" not in message
        assert "generate_soup_tables.py` and commit" in message
        assert "1 line(s) only in the GENERATED file" in message

    def test_a_changed_cell_reads_differently_from_a_removed_row(self):
        changed = self._ROWS.replace("| MADD-ANO-002 | b |", "| MADD-ANO-002 | B |")
        message = gen.describe_drift("doc.md", self._ROWS, changed)
        assert "1 line(s) changed in place" in message
        assert "DO NOT regenerate yet" not in message

        removed = gen.describe_drift(
            "doc.md", self._ROWS,
            self._ROWS.replace("| MADD-ANO-002 | b |\n", ""),
        )
        assert message != removed

    def test_a_mixed_drift_leads_with_the_dangerous_half(self):
        """One row lost and one row gained is still a potential deletion."""
        generated = (
            "| MADD-ANO-001 | a |\n| MADD-ANO-003 | c |\n| MADD-ANO-004 | d |\n"
        )
        message = gen.describe_drift("doc.md", self._ROWS, generated)
        assert "DO NOT regenerate yet" in message
        assert "MADD-ANO-002" in message

    def test_the_unified_diff_is_still_printed(self):
        generated = self._ROWS.replace("| MADD-ANO-002 | b |\n", "")
        message = gen.describe_drift("doc.md", self._ROWS, generated)
        assert "doc.md (committed)" in message
        assert "-| MADD-ANO-002 | b |" in message
