"""The SOUP evidence set must match the sources it summarises.

``docs/validation/soup_package.md`` and
``docs/validation/framework_verification.md`` carry summary tables of
``known_anomalies.yaml``, the ``@verification_benchmark`` registry and
``pyproject.toml``.  They were hand-maintained and drifted: 2 of 5
anomalies, 1 of 4 registered benchmarks, 7 of 12 test packages, and a
version identification two to three releases behind the package.  For
IEC 62304 evidence, drift is itself the finding.

The tables are now generated by ``scripts/generate_soup_tables.py``.
This module runs that script's ``--check`` mode, so a stale table fails
in CI's existing ``pytest tests/compliance/`` step rather than shipping.

The checks could later fold into ``scripts/check_anomalies.py``, which
CI's ``compliance`` job already runs; they live here because that script
was being rewritten concurrently.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

os.environ.setdefault("JAX_PLATFORMS", "cpu")

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "generate_soup_tables.py"

sys.path.insert(0, str(REPO_ROOT / "scripts"))

import generate_soup_tables as gen  # noqa: E402


def _run_check() -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ, "JAX_PLATFORMS": "cpu"},
    )


def test_the_committed_soup_tables_match_a_fresh_generation():
    """A table that has drifted from its source fails here, not in review."""
    result = _run_check()
    assert result.returncode == 0, (
        "docs/validation/ is stale — run "
        "`python scripts/generate_soup_tables.py` and commit the result.\n\n"
        + result.stdout + result.stderr
    )


def test_every_anomaly_in_the_registry_reaches_the_summary_table():
    """The §3 table is complete, whatever the generator did to format it."""
    registry = gen.read_registry()
    rendered = gen.SOUP_PACKAGE.read_text()
    for anomaly in registry["anomalies"]:
        assert anomaly["anomaly_id"] in rendered, (
            f"{anomaly['anomaly_id']} is in known_anomalies.yaml but not in "
            f"soup_package.md"
        )


def test_every_registered_benchmark_reaches_the_verification_index():
    """The verification index is complete against the live registry."""
    benchmarks = gen.load_benchmarks()
    assert benchmarks, "no MADD-VER benchmarks registered — check the imports"
    rendered = gen.FRAMEWORK_VERIFICATION.read_text()
    for benchmark_id in benchmarks:
        assert benchmark_id in rendered, (
            f"{benchmark_id} is registered but missing from "
            f"framework_verification.md"
        )


def test_a_test_module_that_registers_a_benchmark_is_wired_into_the_index():
    """A new benchmark cannot register without joining BENCHMARK_MODULES.

    Without this the index stays green while going incomplete, which is
    how MADD-VER-002/003/004 ended up unlisted.
    """
    assert gen._check_benchmark_modules_are_complete() == []


def test_every_test_package_is_described_in_the_organization_table():
    assert gen._check_test_directories_are_described(gen.test_packages()) == []


def test_the_version_is_identified_the_same_way_everywhere():
    """pyproject is authoritative; the registry and CITATION.cff follow it."""
    assert gen._check_versions(
        gen.read_pyproject(), gen.read_registry(), gen.read_citation()
    ) == []


def test_an_unresolved_anomaly_does_not_record_a_closed_version_range():
    """A reachable defect and a closed version range cannot both be true.

    MADD-ANO-001 and MADD-ANO-002 sat in exactly that state for three
    releases: still reproducible, but recorded as affecting only the
    version they were first seen in.  MADD-ANO-005 was the worse case --
    `partially_resolved` with `<=0.3.0`, asserting 0.4.0 is clean while
    its own `residual_risk` describes the path on which the pre-0.4.0
    behaviour returns.  Only `resolved` and `duplicate` may close a
    range; anything else, including a status nobody has enumerated, may
    not.
    """
    assert gen._check_unresolved_anomalies_are_open_ended(
        gen.read_registry()
    ) == []


@pytest.mark.parametrize("status", ["open", "partially_resolved", "wont_fix",
                                    "probably fine tbh"])
def test_a_closed_range_is_refused_for_every_unresolved_status(status):
    registry = {"anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": status,
        "affected_versions": "0.1.0",
    }]}
    errors = gen._check_unresolved_anomalies_are_open_ended(registry)
    assert len(errors) == 1 and "MADD-ANO-999" in errors[0]


@pytest.mark.parametrize("status", ["resolved", "duplicate"])
def test_a_closed_range_is_allowed_once_the_defect_is_gone(status):
    registry = {"anomalies": [{
        "anomaly_id": "MADD-ANO-999",
        "resolution_status": status,
        "affected_versions": "0.3.0, 0.3.1",
    }]}
    assert gen._check_unresolved_anomalies_are_open_ended(registry) == []


@pytest.mark.parametrize(
    "version, expected",
    [
        ("0.4.0.dev0", True),
        ("1.0.0rc1", True),
        ("0.5.0a2", True),
        ("0.3.1", False),
        ("1.0.0", False),
    ],
)
def test_prerelease_detection_decides_whether_a_release_date_exists(
    version, expected
):
    assert gen.is_prerelease(version) is expected
