"""``modelDescription.xml`` generator for FMI 3.0 (added in v0.3.0).

Reads a :class:`GraphManager`'s public surface together with the
``@stability`` audit registry to emit a minimal FMI 3.0
``modelDescription.xml``.  Conservative by default: only surfaces
tagged ``@stability(STABLE)`` enter the FMU unless the caller opts in
via ``include_evolving=True``.

What's included for v0.3.0:

* ``<fmiModelDescription>`` root with required attributes (FMI 3.0,
  ``modelName``, ``instantiationToken``, units).
* ``<ModelVariables>`` populated from the graph's external-input
  edges and per-node state fields.
* ``<ModelStructure>`` ``<Output>`` and ``<InitialUnknown>`` entries
  consistent with the variables.
* Default experiment block (start / stop / tolerance / step size
  derived from the graph's master timestep).

What's deferred:

* Full ``<UnitDefinitions>`` (the v0.3.0 generator emits the unit
  *strings* attached to inputs but doesn't enumerate them in a
  central registry — FMPy round-trips this fine, but a strict
  importer might prefer the registry form).
* ``<TypeDefinitions>`` — added if/when a consumer asks.
* ``<TypeDefinitions>``-level ``<ClockType>``; clocks are emitted as
  ``<Clock>`` variables (``build_model_description(multi_clock=True)``:
  one constant-interval clock per distinct node timestep, every output
  / input of a node tagged with its clock, off by default so the
  single-clock v0.3.0 surface is unchanged).
"""

from __future__ import annotations

import math
import warnings
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Optional
import xml.etree.ElementTree as ET

import numpy as np

from maddening.core.compliance.metadata import StabilityLevel
from maddening.core.compliance.stability import (
    _STABILITY_REGISTRY,
    stability,
)
from maddening.serialization.json_codec import NON_FINITE_TOKENS


# ---------------------------------------------------------------------------
# Public dataclasses
# ---------------------------------------------------------------------------


_DTYPE_TO_FMI_TYPE = {
    "float32": "Float32",
    "float64": "Float64",
    "int8": "Int8",
    "int16": "Int16",
    "int32": "Int32",
    "int64": "Int64",
    "uint8": "UInt8",
    "uint16": "UInt16",
    "uint32": "UInt32",
    "uint64": "UInt64",
    "bool": "Boolean",
    "bool_": "Boolean",
}

# ``dtype="clock"`` marks an FMI 3.0 ``<Clock>`` variable (no value type).
_CLOCK_DTYPE = "clock"

_CAUSALITIES = {
    "input", "output", "parameter", "local",
    "calculatedParameter", "independent",
}
_VARIABILITIES = {"constant", "fixed", "tunable", "discrete", "continuous"}


@dataclass(frozen=True, kw_only=True)
class FMIVariable:
    """A single entry in the FMU's ``<ModelVariables>`` section.

    Construction is **keyword-only**.  ``node`` and ``field`` were added
    in 0.4.0 between ``unit`` and ``shape``, so a positional call written
    against 0.3.x -- ``FMIVariable("plant.x", 1, "float32", "output",
    "continuous", "", "m", (3,))`` -- silently bound the shape to ``node``
    and left ``shape`` empty.  Keyword-only turns that into a
    ``TypeError`` at the call, and stops any later field ever doing it
    again.

    Attributes
    ----------
    name : str
        FMU variable name.  Convention: ``<node>.<field>`` for
        per-node state fields and for external inputs.
    node, field : str, optional
        The graph node and the state / boundary field this variable
        addresses.  Carried explicitly because ``name`` cannot be split
        back into the pair: a node name may itself contain a ``.`` (FMI
        reads dots as name-space separators, the graph does not), and
        splitting at the first one routed ``rod.A.left_temperature`` to a
        node ``rod`` that does not exist.  ``None`` for variables that do
        not address a field (parameters, clocks, ``time``).
    value_reference : int
        Unique handle the FMU runtime uses to address this variable.
        Generated by :func:`build_model_description`.
    dtype : str
        Python dtype name (``"float32"``, ``"int32"``, ...).
    causality : {"input", "output", "parameter", "local",
                 "calculatedParameter"}
    variability : {"constant", "fixed", "tunable", "discrete",
                   "continuous"}
    description : str, optional
        Human-readable description.
    unit : str, optional
        Unit string (e.g. ``"m"``, ``"N"``).  For an input,
        :func:`build_model_description` takes it from the target node's
        :attr:`~maddening.core.node.BoundaryInputSpec.expected_units`
        when the node declares one; for a parameter, from its
        :class:`~maddening.core.params.ParamSpec` ``units``.
    shape : tuple of int, optional
        Array shape, for FMI 3.0 dynamic arrays.  Empty / None means
        scalar.
    start : str, optional
        Initial value as the XML ``start`` attribute text (FMI 3.0
        requires one for ``parameter`` and ``input`` causality; arrays
        are space-separated in row-major order).
    clocks : tuple of int, optional
        Value references of the ``<Clock>`` variables this variable is
        clocked by (FMI 3.0 ``clocks`` attribute).  A clocked variable
        changes only when one of its clocks ticks.
    interval_decimal : float, optional
        For ``dtype="clock"`` only: the constant tick interval in
        seconds (``intervalVariability="constant"``).
    min, max : float, optional
        Declared bounds (the XML ``min`` / ``max`` attributes).  For
        graph parameters these come from :class:`ParamSpec.bounds`, so
        an importer sees the same envelope the sidecar enforces.
    """
    name: str
    value_reference: int
    dtype: str
    causality: str
    variability: str
    description: str = ""
    unit: str = ""
    node: Optional[str] = None
    field: Optional[str] = None
    shape: Optional[tuple[int, ...]] = None
    start: Optional[str] = None
    min: Optional[float] = None
    max: Optional[float] = None
    clocks: tuple[int, ...] = ()
    interval_decimal: Optional[float] = None

    @property
    def is_clock(self) -> bool:
        return self.dtype == _CLOCK_DTYPE

    def node_field(self) -> tuple[str, str]:
        """The ``(node, field)`` pair this variable addresses.

        Returns the pair the model description recorded.  Falls back to
        splitting :attr:`name` at the first ``.`` for a variable built
        without one (hand-written descriptions, older archives), which is
        the historical behaviour and is correct whenever the node name
        holds no dot.
        """
        if self.node is not None:
            return self.node, self.field or ""
        node, _, field = self.name.partition(".")
        return node, field

    def __post_init__(self) -> None:
        if self.causality not in _CAUSALITIES:
            raise ValueError(
                f"FMIVariable.causality={self.causality!r} not in "
                f"{sorted(_CAUSALITIES)}",
            )
        if self.variability not in _VARIABILITIES:
            raise ValueError(
                f"FMIVariable.variability={self.variability!r} not in "
                f"{sorted(_VARIABILITIES)}",
            )
        if self.dtype != _CLOCK_DTYPE and self.dtype not in _DTYPE_TO_FMI_TYPE:
            raise ValueError(
                f"FMIVariable.dtype={self.dtype!r} not in "
                f"{sorted(_DTYPE_TO_FMI_TYPE)}",
            )
        if self.dtype == _CLOCK_DTYPE and self.interval_decimal is None:
            raise ValueError("a clock variable needs interval_decimal")
        if self.dtype == _CLOCK_DTYPE and self.clocks:
            raise ValueError("a clock cannot itself be clocked")


@dataclass
class ModelDescription:
    """The structured contents of a ``modelDescription.xml`` document.

    Construct via :func:`build_model_description`; serialize to XML
    via :meth:`to_xml`.

    Attributes
    ----------
    model_name : str
        Short identifier for the FMU.  Surfaces in the file name and
        as the ``modelName`` attribute on the root element.
    instantiation_token : str
        A GUID-like string the FMU runtime uses to verify schema
        compatibility on instantiation.  Deterministic — see
        :func:`build_model_description` for the derivation rule.
    fmi_version : str
        FMI standard version.  Defaults to ``"3.0"``.
    generation_tool : str
        Tool string written to ``generationTool`` attribute.
    variables : list[FMIVariable]
        Every variable in the FMU's ``<ModelVariables>`` section.
    default_start_time : float
        Default experiment start time.  Derived from the graph
        configuration if available.
    default_stop_time : float
        Default experiment stop time.
    default_step_size : float
        Default fixed timestep, the ``DefaultExperiment`` ``stepSize``: the
        communication step an importer takes.  Derived from the graph's
        step unless ``build_model_description(default_step_size=...)``
        chose another; :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge`
        refuses to serve a description whose step is not a whole number
        of graph steps.
    default_tolerance : float
        Default tolerance for adaptive solvers.
    fixed_parameters : dict[str, str]
        Graph parameters left out of the ``parameter`` variables because
        the compiled step cannot read them, by FMU name
        (``"<node>.params.<key>"``) with the reason.  Not part of the XML;
        the bridge and the sidecar use it to refuse a write that would be
        reported and never used.
    held_inputs : dict[str, tuple]
        The graph's declared external inputs that the description does
        *not* export (``build_model_description(selected_inputs=...)``),
        by name (``"<node>.<field>"``), each as ``(node, field, shape,
        dtype)``.  Not part of the XML: an importer cannot set them, and
        :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge` holds each at zero
        on every step, as ``GraphManager.step`` does for an input its
        caller omits.  Without it the bridge passed only the exported
        inputs, and a node whose input was left out took its own "input
        missing" branch instead (a ball with no table falls through the
        floor).
    graph_timestep : float or None
        The simulated time one step of the described graph advances
        (``GraphManager.timestep``), which is what one sidecar step -- the
        bridge's ``master_dt`` -- covers.  ``build_model_description``
        records it whatever ``default_step_size`` was chosen; ``None`` for
        a description built by hand, which then has only
        ``default_step_size`` to say what its step is.  Not part of the
        XML.  :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge` refuses a
        ``master_dt`` that differs from it: a bridge stepping a 0.01 s
        graph with ``master_dt=0.005`` ran two graph steps per 0.01 s
        ``doStep`` and labelled a state at 0.10 s with the time 0.05 s.
    """
    model_name: str
    instantiation_token: str
    fmi_version: str = "3.0"
    generation_tool: str = "maddening.fmi"
    variables: list[FMIVariable] = field(default_factory=list)
    default_start_time: float = 0.0
    default_stop_time: float = 1.0
    default_step_size: float = 1.0e-3
    default_tolerance: float = 1.0e-6
    # ``modelIdentifier`` of the FMU binary (``binaries/<platform>/<id>.so``).
    # ``None`` emits no <CoSimulation> element (description-only FMU).
    co_simulation_model_identifier: Optional[str] = None
    # ``{"<node>.params.<key>": reason}``: graph parameters *not* exported
    # because the compiled step cannot read them (not written to the XML).
    # ``FmuTcpBridge`` and ``SidecarConfig(fixed_params=...)`` refuse a new
    # value for any of them.
    fixed_parameters: dict[str, str] = field(default_factory=dict)
    # ``{"<node>.<field>": (node, field, shape, dtype)}``: declared external
    # inputs *not* exported (``selected_inputs``), held at zero by the
    # bridge (not written to the XML).
    held_inputs: dict[str, tuple[str, str, tuple[int, ...], str]] = field(
        default_factory=dict)
    # One graph step in seconds (``GraphManager.timestep``), whatever
    # ``default_step_size`` advertises; the bridge's ``master_dt`` must be
    # it.  ``None`` for a hand-built description (not written to the XML).
    graph_timestep: Optional[float] = None

    def clocks(self) -> list[FMIVariable]:
        """The ``<Clock>`` variables (empty for a single-clock FMU)."""
        return [v for v in self.variables if v.is_clock]

    def to_xml(self) -> str:
        """Serialize this description to an FMI 3.0 ``modelDescription.xml``
        string (UTF-8, with XML declaration).
        """
        root = ET.Element("fmiModelDescription", attrib={
            "fmiVersion": self.fmi_version,
            "modelName": self.model_name,
            "instantiationToken": self.instantiation_token,
            "generationTool": self.generation_tool,
        })

        # <CoSimulation> — the interface type the binary implements (FMI
        # 3.0 §2.4.2; must precede UnitDefinitions).  The MADDENING C
        # wrapper is a plain fixed-step co-simulation slave that can
        # save / restore / serialize its (sidecar-held) state.
        if self.co_simulation_model_identifier:
            ET.SubElement(root, "CoSimulation", attrib={
                "modelIdentifier": self.co_simulation_model_identifier,
                "canGetAndSetFMUState": "true",
                "canSerializeFMUState": "true",
                # the bridge advances whole master steps only (a
                # communication step must be a multiple of the default
                # step size); see FmuTcpBridge.handle("step")
                "canHandleVariableCommunicationStepSize": "false",
                "hasEventMode": "false",
            })

        # <UnitDefinitions> — FMI 3.0 requires every referenced unit to
        # appear here.  Emit one <Unit> per distinct unit string used
        # by any variable.  Empty units are skipped.
        used_units = {v.unit for v in self.variables if v.unit}
        if used_units:
            ud = ET.SubElement(root, "UnitDefinitions")
            for u in sorted(used_units):
                ET.SubElement(ud, "Unit", attrib={"name": u})

        # <DefaultExperiment>
        ET.SubElement(root, "DefaultExperiment", attrib={
            "startTime": repr(self.default_start_time),
            "stopTime": repr(self.default_stop_time),
            "tolerance": repr(self.default_tolerance),
            "stepSize": repr(self.default_step_size),
        })

        # <ModelVariables>
        mv = ET.SubElement(root, "ModelVariables")
        for var in self.variables:
            attrib = {
                "name": var.name,
                "valueReference": str(var.value_reference),
                "causality": var.causality,
                "variability": var.variability,
            }
            if var.description:
                attrib["description"] = var.description
            if var.is_clock:
                # FMI 3.0 §2.2.9: a Clock has no value type; a constant
                # interval is declared inline.
                attrib["intervalVariability"] = "constant"
                interval = var.interval_decimal
                # `__post_init__` refuses a clock without one.
                assert interval is not None
                attrib["intervalDecimal"] = repr(float(interval))
                ET.SubElement(mv, "Clock", attrib=attrib)
                continue
            if var.clocks:
                attrib["clocks"] = " ".join(str(c) for c in var.clocks)
            fmi_type = _DTYPE_TO_FMI_TYPE[var.dtype]
            v_el = ET.SubElement(mv, fmi_type, attrib=attrib)
            if var.unit:
                v_el.set("unit", var.unit)
            if var.start is not None:
                v_el.set("start", var.start)
            # An infinite bound is "no bound", which FMI spells by leaving
            # the attribute out -- and ``min="-inf"`` was not a valid
            # ``xs:float`` literal in the first place.
            if var.min is not None and math.isfinite(var.min):
                v_el.set("min", _xs_float(float(var.min)))
            if var.max is not None and math.isfinite(var.max):
                v_el.set("max", _xs_float(float(var.max)))
            if var.shape:
                # FMI 3.0 dynamic arrays — emit one <Dimension> per axis.
                for dim in var.shape:
                    ET.SubElement(v_el, "Dimension", attrib={"start": str(dim)})

        # <ModelStructure> — FMI 3.0 schema requires child order:
        # Output*, ContinuousStateDerivative*, ClockedState*,
        # InitialUnknown*, EventIndicator*.  Emit Outputs first, then
        # InitialUnknowns.
        ms = ET.SubElement(root, "ModelStructure")
        for var in self.variables:
            if var.causality == "output":
                ET.SubElement(ms, "Output", attrib={
                    "valueReference": str(var.value_reference),
                })
        for var in self.variables:
            # A clocked variable is not an initial unknown (FMI 3.0: its
            # value is defined by the clock's first tick, not by
            # initialisation); fmpy's structure validation enforces this.
            if var.variability in ("continuous", "discrete") and \
                    var.causality in ("output", "local") and not var.clocks:
                ET.SubElement(ms, "InitialUnknown", attrib={
                    "valueReference": str(var.value_reference),
                })

        # Pretty-printable serialization.
        ET.indent(root)
        return ET.tostring(root, encoding="unicode", xml_declaration=True)


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def _ensure_stable_only_or_opt_in(
    surface_name: str,
    include_evolving: bool,
) -> bool:
    """Return True iff the named surface is allowed into the FMU.

    The rule: a variable enters the FMU
    surface iff its source/sink is tagged ``@stability(STABLE)`` and
    the caller explicitly opts it in via the FMU export config — *not*
    by default, to keep the public FMU surface minimal.

    The caller's opt-in is selecting which nodes / fields to export.
    The audit-level check is "are the source/sink classes stable?" —
    that's what this function answers.
    """
    level = _STABILITY_REGISTRY.get(surface_name)
    if level == StabilityLevel.STABLE:
        return True
    if include_evolving and level in (
        StabilityLevel.EVOLVING, StabilityLevel.PROVISIONAL,
    ):
        return True
    return False


def _xs_float(x: float) -> str:
    """``x`` as an XML Schema ``float`` / ``double`` literal.

    ``repr(float("inf"))`` is ``'inf'``, which is not an ``xs:float``
    lexical value, so an FMU carrying a non-finite parameter start used
    to fail schema validation.  The three special values have their own
    spellings (``INF``, ``-INF``, ``NaN``); everything else is ``repr``
    as before, which round-trips a double exactly.
    """
    if math.isnan(x):
        return "NaN"
    if math.isinf(x):
        return "INF" if x > 0 else "-INF"
    return repr(x)


def _advertised_bound(spec, side: int, dtype: str) -> Optional[float]:
    """``ParamSpec.bounds[side]`` as the FMI ``min`` / ``max`` attribute.

    FMI's ``min`` / ``max`` are inclusive, but a ``log`` / ``logit``
    leaf's bound is *open* (``p > lo`` strictly -- ``ParamSpec.check``
    and therefore the sidecar refuse ``p == lo``).  Advertise the
    nearest representable value inside the interval instead, so every
    value the XML declares settable is accepted by ``set_params``.  A
    zero bound's neighbour is a float32 subnormal, which XLA:CPU flushes
    to zero (``jnp.asarray(1e-45) <= 0.0`` is ``True``), so the margin
    is never smaller than the smallest normal.
    """
    if spec is None:
        return None
    b = spec.bounds[side]
    if b is None:
        return None
    if spec.transform not in ("log", "logit"):
        return b
    try:
        dt = np.dtype(dtype)
        if not np.issubdtype(dt, np.floating):
            dt = np.dtype(np.float32)
    except TypeError:
        dt = np.dtype(np.float32)
    fi = np.finfo(dt)
    towards = dt.type(np.inf) if side == 0 else dt.type(-np.inf)
    m = np.nextafter(dt.type(b), towards)
    if abs(m) < fi.tiny:
        m = dt.type(fi.tiny if side == 0 else -fi.tiny)
    return float(m)


@dataclass(frozen=True)
class _ExtView:
    """Duck-typed view of an external input for the builder."""
    target_node: str
    target_field: str
    shape: tuple
    dtype: Any
    description: str = ""
    expected_units: str = ""


def _node_timesteps(graph_manager: Any) -> dict[str, float]:
    """Each node's timestep as the graph's step schedules it.

    A ``GraphManager``'s scheduled timesteps
    (``maddening.core.graph_manager._scheduled_timesteps``): every member of
    a sub-cycling coupling group at the group's largest member timestep,
    because the group solves once per macro step and an importer sees its
    members change only then.  A duck-typed graph without coupling groups
    gives its nodes' own timesteps.
    """
    from maddening.core.graph_manager import _scheduled_timesteps  # noqa: PLC0415

    nodes = getattr(graph_manager, "_nodes", {}) or {}
    own = {
        name: float(getattr(spec, "timestep",
                            getattr(getattr(spec, "node", spec), "delta_t", 0.0)))
        for name, spec in nodes.items()
    }
    groups = getattr(graph_manager, "_coupling_groups", None) or ()
    if not groups:
        return own
    return {name: float(dt) for name, dt in _scheduled_timesteps(nodes, groups).items()}


def _master_timestep(graph_manager: Any) -> float:
    """One step of the graph: the simulated time one sidecar step advances.

    ``GraphManager.timestep`` -- the GCD of the scheduled node timesteps,
    which is the fastest node's timestep on a uniform-rate graph and on a
    multi-rate one whose timesteps divide each other (MADD-ANO-078), and
    shorter or longer than that on the others: 0.001 for nodes at 0.002
    and 0.003, 0.02 for a sub-cycling group of 0.01 and 0.02.  A duck-typed
    graph without that property gives the GCD of its node timesteps; an
    empty graph 1e-3.  (This used to read a ``_base_dt`` attribute nothing
    set and fall back to the smallest node timestep, MADD-ANO-097.)
    """
    from maddening.core.graph_manager import _step_duration  # noqa: PLC0415

    try:
        return float(graph_manager.timestep)
    except (AttributeError, RuntimeError):
        pass
    dts = {name: dt for name, dt in _node_timesteps(graph_manager).items() if dt > 0}
    return float(_step_duration(dts)) if dts else 1.0e-3


def _deterministic_token(parts: Iterable[str]) -> str:
    """Build a stable, GUID-shaped token from a list of strings.

    We don't use Python's ``uuid`` because the token must be a pure
    function of the graph's structural fingerprint (any FMU loader
    refuses to instantiate when the token doesn't match the runtime
    DLL's compile-time token).  See FMI 3.0 §2.2.3.
    """
    import hashlib  # noqa: PLC0415 — stdlib lazy import
    h = hashlib.sha256()
    for part in parts:
        h.update(part.encode("utf-8"))
        h.update(b"\0")
    digest = h.hexdigest()
    # Format as 8-4-4-4-12 GUID for tooling that pattern-matches it.
    return f"{digest[:8]}-{digest[8:12]}-{digest[12:16]}-{digest[16:20]}-{digest[20:32]}"


def _owner(var: "FMIVariable") -> str:
    """``"the <causality> of node 'n', field 'f'"`` for a clash message."""
    if var.node is None:
        return f"the {var.causality} {var.name!r}"
    return f"the {var.causality} of node {var.node!r}, field {var.field!r}"


@stability(StabilityLevel.EVOLVING)
def build_model_description(
    graph_manager: Any,
    *,
    model_name: str,
    selected_inputs: Optional[Iterable[str]] = None,
    selected_outputs: Optional[Iterable[tuple[str, str]]] = None,
    include_evolving: bool = False,
    default_step_size: Optional[float] = None,
    include_parameters: bool = True,
    multi_clock: bool = False,
    model_identifier: Optional[str] = None,
) -> ModelDescription:
    """Build an FMI 3.0 :class:`ModelDescription` from a ``GraphManager``.

    Parameters
    ----------
    graph_manager : GraphManager
        A *compiled* graph.  The structure (nodes, edges, external
        inputs) is read at build time.
    model_name : str
        Identifier the FMU will be called by.  Becomes ``modelName``
        in the XML.
    selected_inputs : iterable of str, optional
        FMU input variables to surface, as ``"<node>.<field>"`` of the
        graph's declared external inputs.  When ``None`` (default),
        every external input is included.  A name the graph does not
        declare is a ``ValueError`` (it used to export nothing in silence).
        A declared input left out is not an FMU variable, but the graph
        still reads it: the bridge holds it at zero on every step, as
        ``GraphManager.step`` does for an input its caller omits, and it is
        listed in :attr:`ModelDescription.held_inputs`.  A ``UserWarning``
        names every such input.
    selected_outputs : iterable of (node, field) tuples, optional
        Which per-node state fields to expose as FMU outputs.  When
        ``None`` (default), every state field of every node is
        included.
    include_evolving : bool, default False
        If ``True``, also include surfaces tagged
        ``@stability(EVOLVING)`` or ``PROVISIONAL``.  Default keeps
        the FMU's public surface minimal — only ``STABLE``-tagged
        sources/sinks contribute.
    default_step_size : float, optional
        Default fixed step size for the FMU's experiment block.  Defaults
        to one step of the graph, ``graph_manager.timestep``: the fastest
        node's timestep on a uniform-rate graph, and on a multi-rate graph
        the GCD of the timesteps as scheduled (a sub-cycling coupling
        group at its largest member timestep), which is what one sidecar
        step advances.  Another value is advertised as the FMU's
        communication step; a bridge serves it only if it is a whole
        number of graph steps.  The graph step itself is recorded as
        :attr:`ModelDescription.graph_timestep` either way.
    include_parameters : bool, default True
        Expose every leaf of ``graph_manager.params["nodes"]`` that the
        compiled step reads as a ``causality="parameter"``,
        ``variability="tunable"`` variable named ``<node>.params.<key>``
        (same stability filter as outputs), with ``description`` /
        ``unit`` from the node's :class:`~maddening.core.params.ParamSpec`.
        These are backed by the graph parameter pytree, so an importer that
        sets one changes the next step without a recompile, and the FMU's
        directional derivatives with respect to them are the real
        ``jax.jvp``.  A leaf the step cannot read -- an ``initial_*``
        condition (the FMU's initial state is already built), a value a
        node consumed when it was constructed (``LBMPipeNode.pipe_radius``)
        or declares in ``static_data_deps`` (``WaveletAdaptiveNode.mass``),
        or one only an unconnected input would read -- is **not** exported:
        setting it would change nothing the FMU computes.  Those are listed
        with the reason in :attr:`ModelDescription.fixed_parameters`, which
        the bridge enforces.
    multi_clock : bool, default False
        Emit one FMI 3.0 ``<Clock>`` (``intervalVariability="constant"``)
        per distinct node timestep among the exported nodes, and tag every
        exported output and external input with the clock of its node
        (``clocks=`` attribute, ``variability="discrete"``): an importer
        then knows that a node on a 10x coarser rate only changes every
        10th master step.  A member of a sub-cycling coupling group is on
        its group's largest member timestep, the only rate at which its
        values change between steps.  Clocks are named ``clock_<k>`` in
        order of increasing interval; every interval is a whole number of
        default steps, and the fastest equals it unless the timesteps do
        not divide each other (nodes at 0.002 and 0.003 run on a 0.001
        step).  Off by default (single-clock, every output continuous),
        so existing FMUs are unchanged.
    model_identifier : str, optional
        Emit a ``<CoSimulation modelIdentifier=...>`` element naming the
        FMU binary (``maddening.fmi.package`` uses ``"maddening_fmu"``).
        ``None`` (default) emits a description-only document.

    Returns
    -------
    ModelDescription

    Raises
    ------
    ValueError
        If *model_name* is exactly ``"NaN"``, ``"Infinity"`` or
        ``"-Infinity"``.  The name goes back to the importer in the
        bridge's ``hello`` reply, where the JSON codec refuses it
        (``MADD-ANO-010``); refusing it here is the only point at which
        the caller still has the name in its hand and can change it.
        See :data:`maddening.serialization.json_codec.NON_FINITE_TOKENS`.
        Also if *selected_inputs* names an input the graph does not
        declare.

    Warns
    -----
    UserWarning
        If *selected_inputs* leaves out a declared external input; the
        message names each one and says it is held at zero.
    """
    if model_name in NON_FINITE_TOKENS:
        # MADD-ANO-010's refusal is otherwise reached from the *reply*
        # side: ``FmuTcpBridge``'s hello carries ``model``, so an FMU with
        # this name answered every connection with an unencodable frame.
        # The bridge now turns that into an error reply rather than a dead
        # worker thread, but an error reply on every hello is still an
        # unusable FMU, and by then the caller is a C wrapper on the far
        # end of a socket with no way to act on the name.
        raise ValueError(
            f"model_name {model_name!r} spells a non-finite JSON token, which "
            f"the FMI wire encoding reserves (MADD-ANO-010): the bridge's "
            f"hello reply carries the model name, and a reply carrying this "
            f"string cannot be written as unambiguous JSON.  Name the model "
            f"something else (a different spelling, such as "
            f"{model_name.lower()!r}, is fine)."
        )
    # Inputs: read external-input edges from the graph manager.  The
    # graph manager exposes them via ``_external_input_specs`` (an
    # internal dict) — we accept a duck-typed view for tests.
    ext_specs = getattr(graph_manager, "_external_input_specs", None)
    if ext_specs is None:
        # A real GraphManager keeps ``_external_inputs`` (a list of
        # ExternalInputSpec); key them ``<node>.<field>`` -- unique, and
        # the same convention as outputs -- and borrow description /
        # units from the target node's boundary_input_spec().
        ext_specs = {}
        for ei in getattr(graph_manager, "_external_inputs", None) or []:
            target = getattr(ei, "target_node", None)
            fld = getattr(ei, "target_field", None)
            if target is None or fld is None:
                continue
            node_spec = (getattr(graph_manager, "_nodes", {}) or {}).get(target)
            node = getattr(node_spec, "node", node_spec)
            bis = {}
            try:
                bis = node.boundary_input_spec() if node is not None else {}
            except Exception:  # noqa: BLE001 - descriptor is advisory
                bis = {}
            declared = bis.get(fld)
            raw_dtype = getattr(ei, "dtype", "float32")
            try:
                dtype_name = np.dtype(raw_dtype).name       # jnp.float32 -> "float32"
            except TypeError:
                dtype_name = str(raw_dtype)
            ext_specs[f"{target}.{fld}"] = _ExtView(
                target_node=target, target_field=fld,
                shape=tuple(getattr(ei, "shape", ()) or ()),
                dtype=dtype_name,
                description=getattr(declared, "description", "") or "",
                expected_units=getattr(declared, "expected_units", "") or "",
            )
    if isinstance(selected_inputs, str):
        raise ValueError(
            f"selected_inputs must be an iterable of input names, not the "
            f"string {selected_inputs!r}; pass [{selected_inputs!r}]")
    selected_input_keys = (
        set(selected_inputs) if selected_inputs is not None
        else set(ext_specs.keys())
    )
    unknown_inputs = sorted(selected_input_keys - set(ext_specs))
    if unknown_inputs:
        raise ValueError(
            f"selected_inputs names {unknown_inputs}, which the graph does not "
            f"declare; declared external inputs: {sorted(ext_specs) or ['(none)']}.  "
            "An unknown name would export nothing and leave the input it was "
            "meant to be held at zero; fix the name."
        )
    held_inputs: dict[str, tuple[str, str, tuple[int, ...], str]] = {}
    for ext_key, ext_spec in ext_specs.items():
        if ext_key in selected_input_keys:
            continue
        held_dtype = getattr(ext_spec, "dtype", "float32")
        if not isinstance(held_dtype, str):
            held_dtype = getattr(held_dtype, "name", str(held_dtype))
        held_inputs[ext_key] = (
            str(getattr(ext_spec, "target_node", "") or ""),
            str(getattr(ext_spec, "target_field", "") or ""),
            tuple(getattr(ext_spec, "shape", ()) or ()),
            held_dtype,
        )
    if held_inputs:
        warnings.warn(
            f"build_model_description: selected_inputs leaves out the declared "
            f"external input(s) {sorted(held_inputs)}, which will be held at "
            "zero on every step.  They are not FMU variables, so no importer "
            "can set them, but the graph still reads them; the bridge passes "
            "zero, as GraphManager.step does for an input it is not given.  "
            "They are listed in ModelDescription.held_inputs.",
            UserWarning, stacklevel=2,
        )

    variables: list[FMIVariable] = []
    next_vr = 1  # FMI uses 1-based valueReference

    # ----- Independent variable (FMI 3.0 §2.2.7 mandates exactly one) -----
    # Time is the universal independent variable for fixed-step / continuous
    # simulation.  FMU loaders (e.g. FMPy) refuse a modelDescription.xml
    # missing it.
    variables.append(FMIVariable(
        name="time",
        value_reference=next_vr,
        dtype="float64",
        causality="independent",
        variability="continuous",
        description="Simulation time (independent variable).",
        unit="s",
    ))
    next_vr += 1

    # ----- Clocks (multi-rate export) -----
    nodes = getattr(graph_manager, "_nodes", {})
    clock_vr_of_dt: dict[float, int] = {}
    node_clock: dict[str, int] = {}
    if multi_clock:
        scheduled = _node_timesteps(graph_manager)
        dts: dict[float, list[str]] = {}
        for node_name, node_spec in nodes.items():
            node = getattr(node_spec, "node", node_spec)
            cls_name = f"{type(node).__module__}.{type(node).__name__}"
            if not _ensure_stable_only_or_opt_in(cls_name, include_evolving):
                continue
            # The scheduled timestep, not the node's own: a sub-cycled
            # member's outputs change once per macro step of its group.
            dt = scheduled[node_name]
            dts.setdefault(dt, []).append(node_name)
        for k, dt in enumerate(sorted(dts)):
            variables.append(FMIVariable(
                name=f"clock_{k}",
                value_reference=next_vr,
                dtype=_CLOCK_DTYPE,
                causality="input",
                variability="discrete",
                description=(
                    f"Rate {dt!r} s: ticks when nodes "
                    f"{', '.join(sorted(dts[dt]))} update."
                ),
                interval_decimal=dt,
            ))
            clock_vr_of_dt[dt] = next_vr
            for n in dts[dt]:
                node_clock[n] = next_vr
            next_vr += 1

    def _clocked(node_name: str) -> tuple[tuple[int, ...], str]:
        """``(clocks, variability)`` for a variable owned by ``node_name``."""
        vr = node_clock.get(node_name)
        return ((vr,), "discrete") if vr is not None else ((), "continuous")

    # ----- Inputs -----
    for ext_key, ext_spec in ext_specs.items():
        if ext_key not in selected_input_keys:
            continue
        dtype = getattr(ext_spec, "dtype", "float32")
        if not isinstance(dtype, str):
            dtype = getattr(dtype, "name", str(dtype))
        shape = tuple(getattr(ext_spec, "shape", ()) or ())
        unit = getattr(ext_spec, "expected_units", "") or ""
        clocks, variability = _clocked(str(getattr(ext_spec, "target_node", "")))
        # FMI 3.0 requires a start value on every input; the graph's own
        # default for an unset external input is zero, so advertise that.
        n_elems = int(np.prod(shape)) if shape else 1
        variables.append(FMIVariable(
            name=ext_key,
            value_reference=next_vr,
            dtype=dtype,
            causality="input",
            variability=variability,
            description=getattr(ext_spec, "description", "") or "",
            unit=unit,
            node=str(getattr(ext_spec, "target_node", "") or ""),
            field=str(getattr(ext_spec, "target_field", "") or ""),
            shape=shape or None,
            clocks=clocks,
            start=" ".join(["0.0"] * n_elems),
        ))
        next_vr += 1

    # ----- Outputs -----
    selected_output_set = (
        set((n, f) for (n, f) in (selected_outputs or []))
    )
    for node_name, node_spec in nodes.items():
        node = getattr(node_spec, "node", node_spec)
        node_class_name = (
            f"{type(node).__module__}.{type(node).__name__}"
        )
        if not _ensure_stable_only_or_opt_in(node_class_name, include_evolving):
            # Node's class isn't part of the public FMU surface yet.
            continue
        for field_name in node.state_fields():
            if selected_outputs is not None and \
                    (node_name, field_name) not in selected_output_set:
                continue
            initial = node.initial_state()[field_name]
            dtype = str(getattr(initial, "dtype", "float32"))
            shape = tuple(getattr(initial, "shape", ()) or ())
            clocks, variability = _clocked(node_name)
            variables.append(FMIVariable(
                name=f"{node_name}.{field_name}",
                value_reference=next_vr,
                dtype=dtype,
                causality="output",
                variability=variability,
                description=f"State field {field_name!r} of node "
                            f"{node_name!r}",
                node=node_name,
                field=field_name,
                shape=shape or None,
                clocks=clocks,
            ))
            next_vr += 1

    # ----- Parameters (graph parameter pytree) -----
    fixed_parameters: dict[str, str] = {}
    if include_parameters:
        used = {v.name for v in variables}
        node_params = getattr(graph_manager, "params", {}) or {}
        node_params = node_params.get("nodes", {}) if isinstance(node_params, dict) else {}
        # Declared callable so the `callable()` guard narrows to something
        # whose return is `Any` rather than `object` (see maddening.core.node).
        specs_fn: Callable[..., Any] | None = getattr(
            graph_manager, "param_specs", None)
        all_specs = specs_fn().get("nodes", {}) if callable(specs_fn) else {}
        # A knob the running step never reads is not advertised: an
        # importer would set it, read it back and see its value, and the
        # FMU would keep computing with the old one.
        unread_fn: Callable[..., Any] | None = getattr(
            graph_manager, "_param_leaves_the_step_cannot_read", None)
        unread = unread_fn() if callable(unread_fn) else {}
        for node_name, leaves in node_params.items():
            node_spec = nodes.get(node_name)
            node = getattr(node_spec, "node", node_spec)
            node_class_name = f"{type(node).__module__}.{type(node).__name__}"
            if not _ensure_stable_only_or_opt_in(node_class_name, include_evolving):
                for key in leaves:
                    fixed_parameters[f"{node_name}.params.{key}"] = (
                        f"{type(node).__name__} is not a stability level this "
                        "FMU exports (STABLE, or EVOLVING / PROVISIONAL with "
                        "include_evolving=True), so none of its variables are "
                        "part of the FMU"
                    )
                continue
            node_specs = all_specs.get(node_name, {})
            for key, leaf in leaves.items():
                # Own namespace, mirroring params["nodes"][node][key]: a
                # parameter may share its key with a state field (a
                # node's initial position, say) and must not clash with
                # the "<node>.<field>" output.
                name = f"{node_name}.params.{key}"
                if (node_name, key) in unread:
                    fixed_parameters[name] = unread[(node_name, key)]
                    continue
                if name in used:  # pragma: no cover - defensive
                    raise ValueError(f"FMU variable name clash: {name!r}")
                used.add(name)
                spec = node_specs.get(key)
                dtype = str(getattr(leaf, "dtype", "float32"))
                shape = tuple(getattr(leaf, "shape", ()) or ())
                flat = np.asarray(leaf).ravel()
                start = " ".join(_xs_float(float(x)) for x in flat)
                variables.append(FMIVariable(
                    name=name,
                    value_reference=next_vr,
                    dtype=dtype,
                    causality="parameter",
                    variability="tunable",
                    description=(
                        (spec.description if spec is not None and spec.description else "")
                        or f"Parameter {key!r} of node {node_name!r}"
                    ),
                    unit=(spec.units if spec is not None else "") or "",
                    shape=shape or None,
                    start=start,
                    min=_advertised_bound(spec, 0, dtype),
                    max=_advertised_bound(spec, 1, dtype),
                ))
                next_vr += 1

    # ----- Name uniqueness -----
    # FMI requires every variable name to be unique.  A graph node name
    # may contain a '.', which FMI reads as a name-space separator, so two
    # different (node, field) pairs can spell the same FMU name -- the one
    # ambiguity carrying ``node``/``field`` on the variable cannot resolve.
    # Refuse the export naming both owners instead of writing an FMU whose
    # variables an importer cannot tell apart.
    seen: dict[str, FMIVariable] = {}
    for var in variables:
        clash = seen.get(var.name)
        if clash is not None:
            raise ValueError(
                f"FMU variable name clash: {var.name!r} would name both "
                f"{_owner(clash)} and {_owner(var)}.  FMI variable names must "
                "be unique and a '.' in a node name is not distinguishable "
                "from the separator; rename one of them."
            )
        seen[var.name] = var

    # ----- Defaults -----
    # One graph step, recorded separately from the advertised step: a
    # caller may advertise a coarser communication step, and the bridge
    # still has to know what one sidecar step covers.
    graph_timestep = _master_timestep(graph_manager)
    if default_step_size is None:
        default_step_size = graph_timestep

    # Deterministic instantiationToken — depends on the schema, so
    # the FMU loader refuses mismatched schemas at instantiation.
    token = _deterministic_token([
        model_name,
        *[f"{v.name}:{v.dtype}:{v.causality}:{v.shape!r}" for v in variables],
        f"step:{default_step_size}",
    ])

    return ModelDescription(
        model_name=model_name,
        instantiation_token=token,
        variables=variables,
        default_step_size=default_step_size,
        co_simulation_model_identifier=model_identifier,
        fixed_parameters=fixed_parameters,
        held_inputs=held_inputs,
        graph_timestep=graph_timestep,
    )


__all__ = [
    "FMIVariable",
    "ModelDescription",
    "build_model_description",
]
