"""``modelDescription.xml`` generator for FMI 3.0 (v0.3.0 §A1).

Reads a :class:`GraphManager`'s public surface together with the
``@stability`` audit registry to emit a minimal FMI 3.0
``modelDescription.xml``.  Conservative by default: only surfaces
tagged ``@stability(STABLE)`` enter the FMU unless the caller opts in
via ``include_evolving=True`` (mirrors STACK_V1 M4's stability gate).

What's included for v0.3.0:

* ``<fmiModelDescription>`` root with required attributes (FMI 3.0,
  ``modelName``, ``instantiationToken``, units).
* ``<ModelVariables>`` populated from the graph's external-input
  edges and per-node state fields.
* ``<ModelStructure>`` ``<Output>`` and ``<InitialUnknown>`` entries
  consistent with the variables.
* Default experiment block (start / stop / tolerance / step size
  derived from the graph's master timestep).

What's deferred:

* Full ``<UnitDefinitions>`` (the v0.3.0 generator emits the unit
  *strings* attached to inputs but doesn't enumerate them in a
  central registry — FMPy round-trips this fine, but a strict
  importer might prefer the registry form).
* ``<TypeDefinitions>`` — added if/when a consumer asks.
* Multi-clock ``<ClockType>`` definitions (designed-in but not
  emitted by default — v0.3.0 ships single-clock per A1).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Optional
import xml.etree.ElementTree as ET

from maddening.core.compliance.metadata import StabilityLevel
from maddening.core.compliance.stability import (
    _STABILITY_REGISTRY,
    stability,
)


# ---------------------------------------------------------------------------
# Public dataclasses
# ---------------------------------------------------------------------------


_DTYPE_TO_FMI_TYPE = {
    "float32": "Float32",
    "float64": "Float64",
    "int8": "Int8",
    "int16": "Int16",
    "int32": "Int32",
    "int64": "Int64",
    "uint8": "UInt8",
    "uint16": "UInt16",
    "uint32": "UInt32",
    "uint64": "UInt64",
    "bool": "Boolean",
    "bool_": "Boolean",
}

_CAUSALITIES = {"input", "output", "parameter", "local", "calculatedParameter"}
_VARIABILITIES = {"constant", "fixed", "tunable", "discrete", "continuous"}


@dataclass(frozen=True)
class FMIVariable:
    """A single entry in the FMU's ``<ModelVariables>`` section.

    Attributes
    ----------
    name : str
        FMU variable name.  Convention: ``<node>.<field>`` for
        per-node state fields, ``<edge_name>`` for external inputs.
    value_reference : int
        Unique handle the FMU runtime uses to address this variable.
        Generated by :func:`build_model_description`.
    dtype : str
        Python dtype name (``"float32"``, ``"int32"``, ...).
    causality : {"input", "output", "parameter", "local",
                 "calculatedParameter"}
    variability : {"constant", "fixed", "tunable", "discrete",
                   "continuous"}
    description : str, optional
        Human-readable description.
    unit : str, optional
        Unit string (e.g. ``"m"``, ``"N"``).  Surfaces through
        :class:`EdgeSpec.expected_units` when available.
    shape : tuple of int, optional
        Array shape, for FMI 3.0 dynamic arrays.  Empty / None means
        scalar.
    """
    name: str
    value_reference: int
    dtype: str
    causality: str
    variability: str
    description: str = ""
    unit: str = ""
    shape: Optional[tuple[int, ...]] = None

    def __post_init__(self) -> None:
        if self.causality not in _CAUSALITIES:
            raise ValueError(
                f"FMIVariable.causality={self.causality!r} not in "
                f"{sorted(_CAUSALITIES)}",
            )
        if self.variability not in _VARIABILITIES:
            raise ValueError(
                f"FMIVariable.variability={self.variability!r} not in "
                f"{sorted(_VARIABILITIES)}",
            )
        if self.dtype not in _DTYPE_TO_FMI_TYPE:
            raise ValueError(
                f"FMIVariable.dtype={self.dtype!r} not in "
                f"{sorted(_DTYPE_TO_FMI_TYPE)}",
            )


@dataclass
class ModelDescription:
    """The structured contents of a ``modelDescription.xml`` document.

    Construct via :func:`build_model_description`; serialize to XML
    via :meth:`to_xml`.

    Attributes
    ----------
    model_name : str
        Short identifier for the FMU.  Surfaces in the file name and
        as the ``modelName`` attribute on the root element.
    instantiation_token : str
        A GUID-like string the FMU runtime uses to verify schema
        compatibility on instantiation.  Deterministic — see
        :func:`build_model_description` for the derivation rule.
    fmi_version : str
        FMI standard version.  Defaults to ``"3.0"``.
    generation_tool : str
        Tool string written to ``generationTool`` attribute.
    variables : list[FMIVariable]
        Every variable in the FMU's ``<ModelVariables>`` section.
    default_start_time : float
        Default experiment start time.  Derived from the graph
        configuration if available.
    default_stop_time : float
        Default experiment stop time.
    default_step_size : float
        Default fixed timestep.  Derived from the graph's master
        timestep.
    default_tolerance : float
        Default tolerance for adaptive solvers.
    """
    model_name: str
    instantiation_token: str
    fmi_version: str = "3.0"
    generation_tool: str = "maddening.fmi"
    variables: list[FMIVariable] = field(default_factory=list)
    default_start_time: float = 0.0
    default_stop_time: float = 1.0
    default_step_size: float = 1.0e-3
    default_tolerance: float = 1.0e-6

    def to_xml(self) -> str:
        """Serialize this description to an FMI 3.0 ``modelDescription.xml``
        string (UTF-8, with XML declaration).
        """
        root = ET.Element("fmiModelDescription", attrib={
            "fmiVersion": self.fmi_version,
            "modelName": self.model_name,
            "instantiationToken": self.instantiation_token,
            "generationTool": self.generation_tool,
        })

        # <DefaultExperiment>
        ET.SubElement(root, "DefaultExperiment", attrib={
            "startTime": repr(self.default_start_time),
            "stopTime": repr(self.default_stop_time),
            "tolerance": repr(self.default_tolerance),
            "stepSize": repr(self.default_step_size),
        })

        # <ModelVariables>
        mv = ET.SubElement(root, "ModelVariables")
        for var in self.variables:
            fmi_type = _DTYPE_TO_FMI_TYPE[var.dtype]
            attrib = {
                "name": var.name,
                "valueReference": str(var.value_reference),
                "causality": var.causality,
                "variability": var.variability,
            }
            if var.description:
                attrib["description"] = var.description
            v_el = ET.SubElement(mv, fmi_type, attrib=attrib)
            if var.unit:
                v_el.set("unit", var.unit)
            if var.shape:
                # FMI 3.0 dynamic arrays — emit one <Dimension> per axis.
                for dim in var.shape:
                    ET.SubElement(v_el, "Dimension", attrib={"start": str(dim)})

        # <ModelStructure>
        ms = ET.SubElement(root, "ModelStructure")
        for var in self.variables:
            if var.causality == "output":
                ET.SubElement(ms, "Output", attrib={
                    "valueReference": str(var.value_reference),
                })
            if var.variability in ("continuous", "discrete") and \
                    var.causality in ("output", "local"):
                ET.SubElement(ms, "InitialUnknown", attrib={
                    "valueReference": str(var.value_reference),
                })

        # Pretty-printable serialization.
        ET.indent(root)
        return ET.tostring(root, encoding="unicode", xml_declaration=True)


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def _ensure_stable_only_or_opt_in(
    surface_name: str,
    include_evolving: bool,
) -> bool:
    """Return True iff the named surface is allowed into the FMU.

    The rule (per the v0.3.0 plan §A1): a variable enters the FMU
    surface iff its source/sink is tagged ``@stability(STABLE)`` and
    the caller explicitly opts it in via the FMU export config — *not*
    by default, to keep the public FMU surface minimal.

    The caller's opt-in is selecting which nodes / fields to export.
    The audit-level check is "are the source/sink classes stable?" —
    that's what this function answers.
    """
    level = _STABILITY_REGISTRY.get(surface_name)
    if level == StabilityLevel.STABLE:
        return True
    if include_evolving and level in (
        StabilityLevel.EVOLVING, StabilityLevel.PROVISIONAL,
    ):
        return True
    return False


def _deterministic_token(parts: Iterable[str]) -> str:
    """Build a stable, GUID-shaped token from a list of strings.

    We don't use Python's ``uuid`` because the token must be a pure
    function of the graph's structural fingerprint (any FMU loader
    refuses to instantiate when the token doesn't match the runtime
    DLL's compile-time token).  See FMI 3.0 §2.2.3.
    """
    import hashlib  # noqa: PLC0415 — stdlib lazy import
    h = hashlib.sha256()
    for part in parts:
        h.update(part.encode("utf-8"))
        h.update(b"\0")
    digest = h.hexdigest()
    # Format as 8-4-4-4-12 GUID for tooling that pattern-matches it.
    return f"{digest[:8]}-{digest[8:12]}-{digest[12:16]}-{digest[16:20]}-{digest[20:32]}"


@stability(StabilityLevel.EVOLVING)
def build_model_description(
    graph_manager: Any,
    *,
    model_name: str,
    selected_inputs: Optional[Iterable[str]] = None,
    selected_outputs: Optional[Iterable[tuple[str, str]]] = None,
    include_evolving: bool = False,
    default_step_size: Optional[float] = None,
) -> ModelDescription:
    """Build an FMI 3.0 :class:`ModelDescription` from a ``GraphManager``.

    Parameters
    ----------
    graph_manager : GraphManager
        A *compiled* graph.  The structure (nodes, edges, external
        inputs) is read at build time.
    model_name : str
        Identifier the FMU will be called by.  Becomes ``modelName``
        in the XML.
    selected_inputs : iterable of str, optional
        FMU input variables to surface.  Names must match the graph's
        registered external-input keys.  When ``None`` (default),
        every external input is included.
    selected_outputs : iterable of (node, field) tuples, optional
        Which per-node state fields to expose as FMU outputs.  When
        ``None`` (default), every state field of every node is
        included.
    include_evolving : bool, default False
        If ``True``, also include surfaces tagged
        ``@stability(EVOLVING)`` or ``PROVISIONAL``.  Default keeps
        the FMU's public surface minimal — only ``STABLE``-tagged
        sources/sinks contribute.
    default_step_size : float, optional
        Default fixed step size for the FMU's experiment block.
        Defaults to the graph's master timestep when available.

    Returns
    -------
    ModelDescription
    """
    # Inputs: read external-input edges from the graph manager.  The
    # graph manager exposes them via ``_external_input_specs`` (an
    # internal dict) — we accept a duck-typed view for tests.
    ext_specs = getattr(graph_manager, "_external_input_specs", {})
    selected_input_keys = (
        set(selected_inputs) if selected_inputs is not None
        else set(ext_specs.keys())
    )

    variables: list[FMIVariable] = []
    next_vr = 1  # FMI uses 1-based valueReference

    # ----- Inputs -----
    for ext_key, ext_spec in ext_specs.items():
        if ext_key not in selected_input_keys:
            continue
        dtype = getattr(ext_spec, "dtype", "float32")
        if not isinstance(dtype, str):
            dtype = getattr(dtype, "name", str(dtype))
        shape = tuple(getattr(ext_spec, "shape", ()) or ())
        unit = getattr(ext_spec, "expected_units", "") or ""
        variables.append(FMIVariable(
            name=ext_key,
            value_reference=next_vr,
            dtype=dtype,
            causality="input",
            variability="continuous",
            description=getattr(ext_spec, "description", "") or "",
            unit=unit,
            shape=shape or None,
        ))
        next_vr += 1

    # ----- Outputs -----
    nodes = getattr(graph_manager, "_nodes", {})
    selected_output_set = (
        set((n, f) for (n, f) in (selected_outputs or []))
    )
    for node_name, node_spec in nodes.items():
        node = getattr(node_spec, "node", node_spec)
        node_class_name = (
            f"{type(node).__module__}.{type(node).__name__}"
        )
        if not _ensure_stable_only_or_opt_in(node_class_name, include_evolving):
            # Node's class isn't part of the public FMU surface yet.
            continue
        for field_name in node.state_fields():
            if selected_outputs is not None and \
                    (node_name, field_name) not in selected_output_set:
                continue
            initial = node.initial_state()[field_name]
            dtype = str(getattr(initial, "dtype", "float32"))
            shape = tuple(getattr(initial, "shape", ()) or ())
            variables.append(FMIVariable(
                name=f"{node_name}.{field_name}",
                value_reference=next_vr,
                dtype=dtype,
                causality="output",
                variability="continuous",
                description=f"State field {field_name!r} of node "
                            f"{node_name!r}",
                shape=shape or None,
            ))
            next_vr += 1

    # ----- Defaults -----
    if default_step_size is None:
        default_step_size = float(
            getattr(graph_manager, "_master_timestep", 1.0e-3) or 1.0e-3
        )

    # Deterministic instantiationToken — depends on the schema, so
    # the FMU loader refuses mismatched schemas at instantiation.
    token = _deterministic_token([
        model_name,
        *[f"{v.name}:{v.dtype}:{v.causality}:{v.shape!r}" for v in variables],
        f"step:{default_step_size}",
    ])

    return ModelDescription(
        model_name=model_name,
        instantiation_token=token,
        variables=variables,
        default_step_size=default_step_size,
    )


__all__ = [
    "FMIVariable",
    "ModelDescription",
    "build_model_description",
]
