"""``modelDescription.xml`` generator for FMI 3.0 (added in v0.3.0).

Reads a :class:`GraphManager`'s public surface together with the
``@stability`` audit registry to emit a minimal FMI 3.0
``modelDescription.xml``.  Conservative by default: only surfaces
tagged ``@stability(STABLE)`` enter the FMU unless the caller opts in
via ``include_evolving=True``.

What's included for v0.3.0:

* ``<fmiModelDescription>`` root with required attributes (FMI 3.0,
  ``modelName``, ``instantiationToken``, units).
* ``<ModelVariables>`` populated from the graph's external-input
  edges and per-node state fields.
* ``<ModelStructure>`` ``<Output>`` and ``<InitialUnknown>`` entries
  consistent with the variables.
* Default experiment block (start / stop / tolerance / step size
  derived from the graph's master timestep).

What's deferred:

* Full ``<UnitDefinitions>`` (the v0.3.0 generator emits the unit
  *strings* attached to inputs but doesn't enumerate them in a
  central registry — FMPy round-trips this fine, but a strict
  importer might prefer the registry form).
* ``<TypeDefinitions>`` — added if/when a consumer asks.
* ``<TypeDefinitions>``-level ``<ClockType>``; clocks are emitted as
  ``<Clock>`` variables (``build_model_description(multi_clock=True)``:
  one constant-interval clock per distinct node timestep, every output
  / input of a node tagged with its clock; off by default, when the
  description has no ``<Clock>`` and no ``clocks=`` attribute).
"""

from __future__ import annotations

import math
import warnings
import weakref
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Optional
import xml.etree.ElementTree as ET

import numpy as np

from maddening.core.compliance.metadata import StabilityLevel
from maddening.core.compliance.stability import (
    _STABILITY_REGISTRY,
    stability,
)
from maddening.serialization.json_codec import NON_FINITE_TOKENS


# ---------------------------------------------------------------------------
# Public dataclasses
# ---------------------------------------------------------------------------


_DTYPE_TO_FMI_TYPE = {
    "float32": "Float32",
    "float64": "Float64",
    "int8": "Int8",
    "int16": "Int16",
    "int32": "Int32",
    "int64": "Int64",
    "uint8": "UInt8",
    "uint16": "UInt16",
    "uint32": "UInt32",
    "uint64": "UInt64",
    "bool": "Boolean",
    "bool_": "Boolean",
}

# ``dtype="clock"`` marks an FMI 3.0 ``<Clock>`` variable (no value type).
_CLOCK_DTYPE = "clock"

_CAUSALITIES = {
    "input", "output", "parameter", "local",
    "calculatedParameter", "independent",
}
_VARIABILITIES = {"constant", "fixed", "tunable", "discrete", "continuous"}


@dataclass(frozen=True, kw_only=True)
class FMIVariable:
    """A single entry in the FMU's ``<ModelVariables>`` section.

    Construction is **keyword-only**.  ``node`` and ``field`` were added
    in 0.4.0 between ``unit`` and ``shape``, so a positional call written
    against 0.3.x -- ``FMIVariable("plant.x", 1, "float32", "output",
    "continuous", "", "m", (3,))`` -- silently bound the shape to ``node``
    and left ``shape`` empty.  Keyword-only turns that into a
    ``TypeError`` at the call, and stops any later field ever doing it
    again.

    Attributes
    ----------
    name : str
        FMU variable name.  Convention: ``<node>.<field>`` for
        per-node state fields and for external inputs.
    node, field : str, optional
        The graph node and the state / boundary field this variable
        addresses.  Carried explicitly because ``name`` cannot be split
        back into the pair: a node name may itself contain a ``.`` (FMI
        reads dots as name-space separators, the graph does not), and
        splitting at the first one routed ``rod.A.left_temperature`` to a
        node ``rod`` that does not exist.  For a parameter, ``node`` and
        ``field`` are the node and its parameter key
        (``params["nodes"][node][field]``): ``<node>.params.<key>`` cannot
        be split back either, when the node's name itself holds
        ``.params.``.  ``None`` for variables that address neither (clocks,
        ``time``).
    value_reference : int
        Unique handle the FMU runtime uses to address this variable.
        Generated by :func:`build_model_description`.
    dtype : str
        Python dtype name (``"float32"``, ``"int32"``, ...).
    causality : {"input", "output", "parameter", "local",
                 "calculatedParameter"}
    variability : {"constant", "fixed", "tunable", "discrete",
                   "continuous"}
    description : str, optional
        Human-readable description.
    unit : str, optional
        Unit string (e.g. ``"m"``, ``"N"``).  For an input,
        :func:`build_model_description` takes it from the target node's
        :attr:`~maddening.core.node.BoundaryInputSpec.expected_units`
        when the node declares one; for a parameter, from its
        :class:`~maddening.core.params.ParamSpec` ``units``.
    shape : tuple of int, optional
        Array shape, for FMI 3.0 dynamic arrays.  Empty / None means
        scalar.
    start : str, optional
        Initial value as the XML ``start`` attribute text (FMI 3.0
        requires one for ``parameter`` and ``input`` causality; arrays
        are space-separated in row-major order), in the lexical form of
        the variable's FMI type: ``true`` / ``false`` for a Boolean, an
        integer literal for an integer type, an ``xs:double`` literal for
        a float.  :meth:`ModelDescription.to_xml` rewrites a start given
        in another form (``"0.0"`` for an Int32) into that one.
    clocks : tuple of int, optional
        Value references of the ``<Clock>`` variables this variable is
        clocked by (FMI 3.0 ``clocks`` attribute).  A clocked variable
        changes only when one of its clocks ticks.
    interval_decimal : float, optional
        For ``dtype="clock"`` only: the constant tick interval in
        seconds (``intervalVariability="constant"``).
    min, max : float, optional
        Declared bounds (the XML ``min`` / ``max`` attributes).  For
        graph parameters these come from :class:`ParamSpec.bounds`, so
        an importer sees the same envelope the sidecar enforces: an open
        ``log`` / ``logit`` bound is advertised as the outermost value
        inside it that ``ParamSpec.check`` accepts in the leaf's dtype --
        the next float in, unless the transform's arithmetic rounds that
        onto the bound (a float32 ``logit`` under ``(-1, 1)``, whose
        ``max`` is then two floats in).  The bridge refuses to serve the
        description once its graph's spec changes (``set_param_spec``).
    """
    name: str
    value_reference: int
    dtype: str
    causality: str
    variability: str
    description: str = ""
    unit: str = ""
    node: Optional[str] = None
    field: Optional[str] = None
    shape: Optional[tuple[int, ...]] = None
    start: Optional[str] = None
    min: Optional[float] = None
    max: Optional[float] = None
    clocks: tuple[int, ...] = ()
    interval_decimal: Optional[float] = None

    @property
    def is_clock(self) -> bool:
        return self.dtype == _CLOCK_DTYPE

    def node_field(self) -> tuple[str, str]:
        """The ``(node, field)`` pair this variable addresses.

        Returns the pair the model description recorded.  Falls back to
        splitting :attr:`name` at the first ``.`` for a variable built
        without one (hand-written descriptions, older archives), which is
        the historical behaviour and is correct whenever the node name
        holds no dot.
        """
        if self.node is not None:
            return self.node, self.field or ""
        node, _, field = self.name.partition(".")
        return node, field

    def __post_init__(self) -> None:
        if self.causality not in _CAUSALITIES:
            raise ValueError(
                f"FMIVariable.causality={self.causality!r} not in "
                f"{sorted(_CAUSALITIES)}",
            )
        if self.variability not in _VARIABILITIES:
            raise ValueError(
                f"FMIVariable.variability={self.variability!r} not in "
                f"{sorted(_VARIABILITIES)}",
            )
        if self.dtype != _CLOCK_DTYPE and self.dtype not in _DTYPE_TO_FMI_TYPE:
            raise ValueError(
                f"FMIVariable.dtype={self.dtype!r} not in "
                f"{sorted(_DTYPE_TO_FMI_TYPE)}",
            )
        if self.dtype == _CLOCK_DTYPE and self.interval_decimal is None:
            raise ValueError("a clock variable needs interval_decimal")
        if self.dtype == _CLOCK_DTYPE and self.clocks:
            raise ValueError("a clock cannot itself be clocked")


@dataclass
class ModelDescription:
    """The structured contents of a ``modelDescription.xml`` document.

    Construct via :func:`build_model_description`; serialize to XML
    via :meth:`to_xml`.

    Attributes
    ----------
    model_name : str
        Short identifier for the FMU.  Surfaces in the file name and
        as the ``modelName`` attribute on the root element.
    instantiation_token : str
        A GUID-like string the FMU runtime uses to verify schema
        compatibility on instantiation.  Deterministic: a hash of the
        model name, the default step size and, for every variable, its
        name, value reference, type, causality, variability, shape,
        start, min, max, unit and clocks (a clock's interval too).  So an
        FMU whose ``modelDescription.xml`` advertises other start values,
        bounds or units than the description a bridge serves does not
        instantiate against that bridge.  Not covered: a variable's
        ``description`` text.
    fmi_version : str
        FMI standard version.  Defaults to ``"3.0"``.
    generation_tool : str
        Tool string written to ``generationTool`` attribute.
    variables : list[FMIVariable]
        Every variable in the FMU's ``<ModelVariables>`` section.
    default_start_time : float
        Default experiment start time.  Derived from the graph
        configuration if available.
    default_stop_time : float
        Default experiment stop time.
    default_step_size : float
        Default fixed timestep, the ``DefaultExperiment`` ``stepSize``: the
        communication step an importer takes.  Derived from the graph's
        step unless ``build_model_description(default_step_size=...)``
        chose another; :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge`
        refuses to serve a description whose step is not a whole number
        of graph steps.
    default_tolerance : float
        Default tolerance for adaptive solvers.
    fixed_parameters : dict[str, str]
        Graph parameters left out of the ``parameter`` variables because
        the compiled step cannot read them, by FMU name
        (``"<node>.params.<key>"``) with the reason.  Not part of the XML;
        the bridge and the sidecar use it to refuse a write that would be
        reported and never used.
    held_inputs : dict[str, tuple]
        The graph's declared external inputs that the description does
        *not* export (``build_model_description(selected_inputs=...)``),
        by name (``"<node>.<field>"``), each as ``(node, field, shape,
        dtype)``.  Not part of the XML: an importer cannot set them, and
        :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge` holds each at zero
        on every step, as ``GraphManager.step`` does for an input its
        caller omits.  Without it the bridge passed only the exported
        inputs, and a node whose input was left out took its own "input
        missing" branch instead (a ball with no table falls through the
        floor).
    graph_timestep : float or None
        The simulated time one step of the described graph advances
        (``GraphManager.timestep``), which is what one sidecar step -- the
        bridge's ``master_dt`` -- covers.  ``build_model_description``
        records it whatever ``default_step_size`` was chosen; ``None`` for
        a description built by hand, which then has only
        ``default_step_size`` to say what its step is.  Not part of the
        XML.  :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge` refuses a
        ``master_dt`` that differs from it: a bridge stepping a 0.01 s
        graph with ``master_dt=0.005`` ran two graph steps per 0.01 s
        ``doStep`` and labelled a state at 0.10 s with the time 0.05 s.
    """
    model_name: str
    instantiation_token: str
    fmi_version: str = "3.0"
    generation_tool: str = "maddening.fmi"
    variables: list[FMIVariable] = field(default_factory=list)
    default_start_time: float = 0.0
    default_stop_time: float = 1.0
    default_step_size: float = 1.0e-3
    default_tolerance: float = 1.0e-6
    # ``modelIdentifier`` of the FMU binary (``binaries/<platform>/<id>.so``).
    # ``None`` emits no <CoSimulation> element (description-only FMU).
    co_simulation_model_identifier: Optional[str] = None
    # ``{"<node>.params.<key>": reason}``: graph parameters *not* exported
    # because the compiled step cannot read them (not written to the XML).
    # ``FmuTcpBridge`` and ``SidecarConfig(fixed_params=...)`` refuse a new
    # value for any of them.
    fixed_parameters: dict[str, str] = field(default_factory=dict)
    # ``{"<node>.<field>": (node, field, shape, dtype)}``: declared external
    # inputs *not* exported (``selected_inputs``), held at zero by the
    # bridge (not written to the XML).
    held_inputs: dict[str, tuple[str, str, tuple[int, ...], str]] = field(
        default_factory=dict)
    # One graph step in seconds (``GraphManager.timestep``), whatever
    # ``default_step_size`` advertises; the bridge's ``master_dt`` must be
    # it.  ``None`` for a hand-built description (not written to the XML).
    graph_timestep: Optional[float] = None
    # The graph the description was built from (a weak reference) and which
    # of its compiles (``GraphManager._compile_generation``).  Set by
    # ``build_model_description``, ``None`` for a hand-built description;
    # not written to the XML.  ``FmuTcpBridge`` refuses to serve the
    # description once that graph has changed or been compiled again, or
    # with a sidecar running another compile's step.
    _graph: Optional[Callable[[], Any]] = field(
        default=None, init=False, repr=False, compare=False)
    _graph_generation: Optional[int] = field(
        default=None, init=False, repr=False, compare=False)

    def clocks(self) -> list[FMIVariable]:
        """The ``<Clock>`` variables (empty for a single-clock FMU)."""
        return [v for v in self.variables if v.is_clock]

    def to_xml(self) -> str:
        """Serialize this description to an FMI 3.0 ``modelDescription.xml``
        string (UTF-8, with XML declaration).
        """
        root = ET.Element("fmiModelDescription", attrib={
            "fmiVersion": self.fmi_version,
            "modelName": self.model_name,
            "instantiationToken": self.instantiation_token,
            "generationTool": self.generation_tool,
        })

        # <CoSimulation> — the interface type the binary implements (FMI
        # 3.0 §2.4.2; must precede UnitDefinitions).  The MADDENING C
        # wrapper is a plain fixed-step co-simulation slave that can
        # save / restore / serialize its (sidecar-held) state.
        if self.co_simulation_model_identifier:
            ET.SubElement(root, "CoSimulation", attrib={
                "modelIdentifier": self.co_simulation_model_identifier,
                "canGetAndSetFMUState": "true",
                "canSerializeFMUState": "true",
                # the bridge advances whole master steps only (a
                # communication step must be a multiple of the default
                # step size); see FmuTcpBridge.handle("step")
                "canHandleVariableCommunicationStepSize": "false",
                "hasEventMode": "false",
            })

        # <UnitDefinitions> — FMI 3.0 requires every referenced unit to
        # appear here.  Emit one <Unit> per distinct unit string used
        # by any variable.  Empty units are skipped.
        used_units = {v.unit for v in self.variables if v.unit}
        if used_units:
            ud = ET.SubElement(root, "UnitDefinitions")
            for u in sorted(used_units):
                ET.SubElement(ud, "Unit", attrib={"name": u})

        # <DefaultExperiment>
        ET.SubElement(root, "DefaultExperiment", attrib={
            "startTime": repr(self.default_start_time),
            "stopTime": repr(self.default_stop_time),
            "tolerance": repr(self.default_tolerance),
            "stepSize": repr(self.default_step_size),
        })

        # <ModelVariables>
        mv = ET.SubElement(root, "ModelVariables")
        for var in self.variables:
            attrib = {
                "name": var.name,
                "valueReference": str(var.value_reference),
                "causality": var.causality,
                "variability": var.variability,
            }
            if var.description:
                attrib["description"] = var.description
            if var.is_clock:
                # FMI 3.0 §2.2.9: a Clock has no value type; a constant
                # interval is declared inline.
                attrib["intervalVariability"] = "constant"
                interval = var.interval_decimal
                # `__post_init__` refuses a clock without one.
                assert interval is not None
                attrib["intervalDecimal"] = repr(float(interval))
                ET.SubElement(mv, "Clock", attrib=attrib)
                continue
            if var.clocks:
                attrib["clocks"] = " ".join(str(c) for c in var.clocks)
            fmi_type = _DTYPE_TO_FMI_TYPE[var.dtype]
            v_el = ET.SubElement(mv, fmi_type, attrib=attrib)
            if var.unit:
                v_el.set("unit", var.unit)
            if var.start is not None:
                # In the lexical form of the variable's type: FMI 3.0's
                # schema refuses "0.0" for a Boolean or an Int32.
                v_el.set("start", _xs_start(var.start, var.dtype))
            # An infinite bound is "no bound", which FMI spells by leaving
            # the attribute out -- and ``min="-inf"`` was not a valid
            # ``xs:float`` literal in the first place.  The bound is written
            # in the type's own form too, and not at all for a Boolean,
            # which has no min / max.
            for side, (attr, bound) in enumerate((("min", var.min), ("max", var.max))):
                if bound is None:
                    continue
                literal = _xs_bound(float(bound), var.dtype, side)
                if literal is not None:
                    v_el.set(attr, literal)
            if var.shape:
                # FMI 3.0 dynamic arrays — emit one <Dimension> per axis.
                for dim in var.shape:
                    ET.SubElement(v_el, "Dimension", attrib={"start": str(dim)})

        # <ModelStructure> — FMI 3.0 schema requires child order:
        # Output*, ContinuousStateDerivative*, ClockedState*,
        # InitialUnknown*, EventIndicator*.  Emit Outputs first, then
        # InitialUnknowns.
        ms = ET.SubElement(root, "ModelStructure")
        for var in self.variables:
            if var.causality == "output":
                ET.SubElement(ms, "Output", attrib={
                    "valueReference": str(var.value_reference),
                })
        for var in self.variables:
            # A clocked variable is not an initial unknown (FMI 3.0: its
            # value is defined by the clock's first tick, not by
            # initialisation); fmpy's structure validation enforces this.
            if var.variability in ("continuous", "discrete") and \
                    var.causality in ("output", "local") and not var.clocks:
                ET.SubElement(ms, "InitialUnknown", attrib={
                    "valueReference": str(var.value_reference),
                })

        # Pretty-printable serialization.
        ET.indent(root)
        return ET.tostring(root, encoding="unicode", xml_declaration=True)


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def _ensure_stable_only_or_opt_in(
    surface_name: str,
    include_evolving: bool,
) -> bool:
    """Return True iff the named surface is allowed into the FMU.

    The rule: a variable enters the FMU
    surface iff its source/sink is tagged ``@stability(STABLE)`` and
    the caller explicitly opts it in via the FMU export config — *not*
    by default, to keep the public FMU surface minimal.

    The caller's opt-in is selecting which nodes / fields to export.
    The audit-level check is "are the source/sink classes stable?" —
    that's what this function answers.
    """
    level = _STABILITY_REGISTRY.get(surface_name)
    if level == StabilityLevel.STABLE:
        return True
    if include_evolving and level in (
        StabilityLevel.EVOLVING, StabilityLevel.PROVISIONAL,
    ):
        return True
    return False


def _xs_float(x: float) -> str:
    """``x`` as an XML Schema ``float`` / ``double`` literal.

    ``repr(float("inf"))`` is ``'inf'``, which is not an ``xs:float``
    lexical value, so an FMU carrying a non-finite parameter start used
    to fail schema validation.  The three special values have their own
    spellings (``INF``, ``-INF``, ``NaN``); everything else is ``repr``
    as before, which round-trips a double exactly.
    """
    if math.isnan(x):
        return "NaN"
    if math.isinf(x):
        return "INF" if x > 0 else "-INF"
    return repr(x)


def _fmi_kind(dtype: str) -> str:
    """``"bool"``, ``"int"`` or ``"float"``: the lexical family of ``dtype``'s
    FMI type (``_DTYPE_TO_FMI_TYPE``)."""
    fmi_type = _DTYPE_TO_FMI_TYPE[dtype]
    if fmi_type == "Boolean":
        return "bool"
    return "float" if fmi_type.startswith("Float") else "int"


def _xs_value(x: Any, dtype: str) -> str:
    """One value as the XML Schema literal of ``dtype``'s FMI type.

    FMI 3.0's schema types a ``<Boolean>``'s ``start`` as ``xs:boolean``
    and an ``<Int32>``'s as ``xs:int`` (and so on for every integer
    width), so the ``"0.0"`` and ``"1.0"`` every input and parameter used
    to get are not valid there: FMPy's ``validate_fmu`` reported them, and
    its ``simulate_fmu``, which validates by default, refused the FMU.
    """
    kind = _fmi_kind(dtype)
    if kind == "bool":
        return "true" if bool(x) else "false"
    if kind == "int":
        return str(int(x))
    return _xs_float(float(x))


def _parse_xs_value(token: str, dtype: str) -> Any:
    """A ``start`` token back as a Python value of ``dtype``'s family.

    The inverse of :func:`_xs_value`, and lenient about the form: a float
    literal is accepted for an integer or Boolean variable when it is
    integral (``"0.0"``, which descriptions before 0.4.0's fix carried),
    and ``"1"`` / ``"0"`` for a Boolean, as ``xs:boolean`` allows.

    Raises
    ------
    ValueError
        If the token is not a value of the type (``"0.5"`` for an Int32,
        ``"2"`` for a Boolean, ``"yes"``).
    """
    kind = _fmi_kind(dtype)
    text = token.strip()
    if kind == "bool":
        if text in ("true", "false"):
            return text == "true"
        number = float(text)
        if number not in (0.0, 1.0):
            raise ValueError(f"{token!r} is not a Boolean value")
        return number == 1.0
    if kind == "int":
        try:
            return int(text)
        except ValueError:
            number = float(text)
            if not number.is_integer():
                raise ValueError(f"{token!r} is not an integer value") from None
            return int(number)
    return float(text)


def _xs_start(start: str, dtype: str) -> str:
    """``start`` rewritten into the lexical form of ``dtype``'s FMI type,
    token by token; a token that is not a value of the type is kept as it
    is (schema validation then names it)."""
    out = []
    for token in start.split():
        try:
            out.append(_xs_value(_parse_xs_value(token, dtype), dtype))
        except (ValueError, OverflowError):
            out.append(token)
    return " ".join(out)


def _xs_bound(bound: float, dtype: str, side: int) -> Optional[str]:
    """A ``min`` (``side=0``) or ``max`` (``side=1``) as the literal of
    ``dtype``'s FMI type, or ``None`` for no attribute.

    A Boolean has no ``min`` / ``max`` in FMI 3.0's schema.  An integer
    type's bound is the nearest integer inside the interval (``ceil`` for
    ``min``, ``floor`` for ``max``), and is left out where it lies beyond
    the type's own range, which already bounds every value.  A float bound
    is an ``xs:double`` literal, as before.
    """
    kind = _fmi_kind(dtype)
    if kind == "bool" or not math.isfinite(bound):
        return None
    if kind == "float":
        return _xs_float(float(bound))
    info = np.iinfo(np.dtype(dtype))
    value = math.ceil(bound) if side == 0 else math.floor(bound)
    if (side == 0 and value <= info.min) or (side == 1 and value >= info.max):
        return None
    if value < info.min or value > info.max:
        return None
    return str(value)


_BOUND_SEARCH_DOUBLINGS = 2200
"""How many times :func:`_accepted_inside` may double its distance from an
open bound looking for a value ``ParamSpec.check`` accepts: enough to cross
float64's whole range from its smallest subnormal spacing (2**-1074 to
2**1024 is about 2100 doublings), so the search never stops short of the
interval's middle for want of steps."""


def _accepted_inside(spec, b: float, side: int, dt: np.dtype,
                     first: Any) -> Optional[Any]:
    """The outermost value of dtype ``dt`` at or inside ``first`` (which
    lies inside the open bound ``b``) that ``spec.check`` accepts, or
    ``None`` when none does on this side of the interval's middle.

    ``check`` decides with the transform's own arithmetic, so a value one
    float inside an open bound may still be refused: a float32 ``logit``
    under ``(-1, 1)`` computes ``(p - lo) / (hi - lo)`` as exactly 1 for
    ``nextafter(1, 0)``, and a bound whose float spacing is subnormal
    (``TINY <= |b| < 2**-102`` in float32) is one flushed distance from its
    neighbour.  Acceptance is monotone moving inward from a bound, so the
    search doubles the distance from ``b`` until a value is accepted, then
    bisects between that and the last refused one.
    """
    t = dt.type
    inward = 1.0 if side == 0 else -1.0

    def accepts(x) -> bool:
        try:
            spec.check(np.asarray(x, dtype=dt))
        except ValueError:
            return False
        return True

    if accepts(first):
        return first
    other = spec.bounds[1 - side]
    middle = (0.5 * (b + float(other)) if other is not None
              else inward * float(np.finfo(dt).max))
    refused, accepted = first, None
    distance = abs(float(first) - b)
    for _ in range(_BOUND_SEARCH_DOUBLINGS):
        distance *= 2.0
        with np.errstate(over="ignore"):
            candidate = t(b + inward * distance)
        if not np.isfinite(candidate) or inward * (float(candidate) - middle) > 0:
            return None
        if inward * (float(candidate) - float(refused)) <= 0:
            continue                                  # rounded back to the last one
        if accepts(candidate):
            accepted = candidate
            break
        refused = candidate
    if accepted is None:
        return None
    while True:
        mid = t(0.5 * (float(refused) + float(accepted)))
        if mid == refused or mid == accepted:
            return accepted
        if accepts(mid):
            accepted = mid
        else:
            refused = mid


def _advertised_bound(spec, side: int, dtype: str) -> Optional[float]:
    """``ParamSpec.bounds[side]`` as the FMI ``min`` / ``max`` attribute.

    FMI's ``min`` / ``max`` are inclusive, but a ``log`` / ``logit``
    leaf's bound is *open* (``p > lo`` strictly -- ``ParamSpec.check``
    and therefore the sidecar refuse ``p == lo``), and a ``log`` leaf with
    no lower bound is bounded below by 0 all the same.  Advertise the
    nearest representable value inside the interval instead, so every
    value the XML declares settable is accepted by ``set_params``.  A
    zero bound's neighbour is a float32 subnormal, which XLA:CPU flushes
    to zero (``jnp.asarray(1e-45) <= 0.0`` is ``True``), so the margin
    is never smaller than the smallest normal.

    That neighbour is advertised only if ``ParamSpec.check`` accepts it in
    the leaf's dtype; otherwise the outermost value further in that it
    accepts is (:func:`_accepted_inside`).  ``check`` judges a ``log`` /
    ``logit`` value by the transform's own arithmetic, and the neighbour
    used to be advertised regardless: a float32 ``logit`` leaf under
    ``(-1, 1)`` advertised ``max = nextafter(1, 0)``, whose ``(p - lo) /
    (hi - lo)`` rounds to 1, so a sidecar with ``param_specs`` -- and FMPy
    through the compiled wrapper -- refused the FMU's own advertised max;
    and a bound in float32's subnormal-spacing band (``TINY <= |b| <
    2**-102``) advertised a neighbour one flushed distance away.  When no
    value on the bound's side of the interval passes (a ``logit`` range
    with no float inside it), the neighbour is advertised as before, and
    the bridge refuses a description whose ``min`` exceeds its ``max``.
    """
    if spec is None:
        return None
    b = spec.bounds[side]
    if b is None and side == 0 and spec.transform == "log":
        # ``transform="log"`` without a lower bound is measured from 0
        # (``ParamSpec``: "lo = bounds[0] or 0; p > lo strictly"), and the
        # graph refuses p <= 0 there.  It used to be advertised with no
        # ``min`` at all, so a bridge whose sidecar had no specs accepted
        # and ran mass = -1.
        b = 0.0
    if b is None:
        return None
    if spec.transform not in ("log", "logit"):
        return b
    try:
        dt = np.dtype(dtype)
        if not np.issubdtype(dt, np.floating):
            dt = np.dtype(np.float32)
    except TypeError:
        dt = np.dtype(np.float32)
    fi = np.finfo(dt)
    towards = dt.type(np.inf) if side == 0 else dt.type(-np.inf)
    m = np.nextafter(dt.type(b), towards)
    if abs(m) < fi.tiny:
        m = dt.type(fi.tiny if side == 0 else -fi.tiny)
    import jax  # noqa: PLC0415 - the dtype JAX would hold a leaf of this dtype in

    if jax.dtypes.canonicalize_dtype(dt) != dt:
        # A float64 variable without x64: no leaf of this dtype exists in
        # this process for ``check`` to judge (JAX would hold it as float32).
        return float(m)
    accepted = _accepted_inside(spec, float(b), side, dt, m)
    return float(m if accepted is None else accepted)


def _envelope(lo: Optional[float], hi: Optional[float]) -> tuple[Optional[float], Optional[float]]:
    """``(min, max)`` for comparison: an infinite bound pointing outward is
    no bound (``ParamSpec`` reads ``-inf`` / ``inf`` there as ``None``, and
    :meth:`ModelDescription.to_xml` leaves such an attribute out)."""
    return (None if lo is None or float(lo) == -math.inf else float(lo),
            None if hi is None or float(hi) == math.inf else float(hi))


def _parameter_envelope(spec, dtype: str) -> tuple[Optional[float], Optional[float], str]:
    """``(min, max, unit)`` a parameter variable of ``dtype`` advertises
    under ``spec`` (``None`` for no spec): what
    :func:`build_model_description` writes, and what the bridge compares
    the graph's current declaration with (:func:`_specs_changed_since`)."""
    return (_advertised_bound(spec, 0, dtype), _advertised_bound(spec, 1, dtype),
            (spec.units if spec is not None else "") or "")


def _specs_changed_since(md: "ModelDescription", graph_manager: Any) -> Optional[str]:
    """Why the parameter envelope ``md`` advertises is no longer the one
    ``graph_manager`` declares, or ``None``.

    ``GraphManager.set_param_spec`` changes a parameter's ``ParamSpec``
    without dirtying the graph (specs are metadata to the step), so neither
    the compile generation nor the dirty flag sees it.  A description built
    before such a change advertises the old ``min`` / ``max`` / ``unit``,
    while a sidecar built after it from ``gm.param_specs()`` enforces the
    new ones: a bridge then accepted values outside the bounds its XML (and
    its instantiation token) advertise, or refused values inside them.
    Each exported parameter's envelope is derived again from the graph's
    current spec, exactly as the description derived it, and compared.
    """
    # Declared callable so the guard narrows to something whose return is
    # ``Any`` (as in build_model_description).
    specs_fn: Callable[..., Any] | None = getattr(graph_manager, "param_specs", None)
    if not callable(specs_fn):
        return None
    declared = (specs_fn() or {}).get("nodes", {}) or {}
    for var in md.variables:
        if var.causality != "parameter" or var.node is None or not var.field:
            continue
        spec = (declared.get(var.node) or {}).get(var.field)
        now = _parameter_envelope(spec, var.dtype)
        then = (var.min, var.max, var.unit or "")
        if (*_envelope(now[0], now[1]), now[2]) != (*_envelope(then[0], then[1]), then[2]):
            return (f"the ParamSpec of {var.name!r} has changed since "
                    f"(GraphManager.set_param_spec): the description advertises "
                    f"min={then[0]!r}, max={then[1]!r}, unit={then[2]!r}, and the graph "
                    f"now declares min={now[0]!r}, max={now[1]!r}, unit={now[2]!r}")
    return None


@dataclass(frozen=True)
class _ExtView:
    """Duck-typed view of an external input for the builder."""
    target_node: str
    target_field: str
    shape: tuple
    dtype: Any
    description: str = ""
    expected_units: str = ""


def _node_timesteps(graph_manager: Any) -> dict[str, float]:
    """Each node's timestep as the graph's step schedules it.

    A ``GraphManager``'s scheduled timesteps
    (``maddening.core.graph_manager._scheduled_timesteps``): every member of
    a sub-cycling coupling group at the group's largest member timestep,
    because the group solves once per macro step and an importer sees its
    members change only then.  A duck-typed graph without coupling groups
    gives its nodes' own timesteps.
    """
    from maddening.core._graph_specs import _scheduled_timesteps  # noqa: PLC0415

    nodes = getattr(graph_manager, "_nodes", {}) or {}
    own = {
        name: float(getattr(spec, "timestep",
                            getattr(getattr(spec, "node", spec), "delta_t", 0.0)))
        for name, spec in nodes.items()
    }
    groups = getattr(graph_manager, "_coupling_groups", None) or ()
    if not groups:
        return own
    return {name: float(dt) for name, dt in _scheduled_timesteps(nodes, groups).items()}


def _graph_changed_since(graph_manager: Any,
                         generation: Optional[int] = None) -> Optional[str]:
    """Why ``graph_manager``'s compiled step is not the model the graph
    runs next -- or is not its compile ``generation`` -- or ``None``.

    Takes in every pending ``node.params`` write first, with the sync each
    graph entry point runs (``_check_static_data_dirty``), so a structural
    write -- a value the step bakes in when it is traced, such as
    ``HeatNode``'s ``stencil_order`` -- is seen as the change it is.  An
    object without that machinery (a duck-typed view, which has no
    compiled step to disagree with) gives ``None``.
    """
    check = getattr(graph_manager, "_check_static_data_dirty", None)
    if not callable(check):
        return None
    check()
    if getattr(graph_manager, "_compiled_step", None) is None:
        return "the graph has not been compiled"
    if getattr(graph_manager, "_dirty", False):
        return ("the graph has changed since its last compile() -- a structural "
                "node.params write (a value the compiled step bakes in when it is "
                "traced, such as HeatNode's stencil_order), a node, edge, external "
                "input or coupling group added or removed, or a node's static_data "
                "-- so its next run recompiles, and its compiled step is the old "
                "model")
    current = getattr(graph_manager, "_compile_generation", None)
    if generation is not None and current != generation:
        return (f"the graph has been compiled again since (its compile {current}, "
                f"not {generation})")
    return None


def _master_timestep(graph_manager: Any) -> float:
    """One step of the graph: the simulated time one sidecar step advances.

    ``GraphManager.timestep`` -- the GCD of the scheduled node timesteps,
    which is the fastest node's timestep on a uniform-rate graph and on a
    multi-rate one whose timesteps divide each other (MADD-ANO-078), and
    shorter or longer than that on the others: 0.001 for nodes at 0.002
    and 0.003, 0.02 for a sub-cycling group of 0.01 and 0.02.  A duck-typed
    graph without that property gives the GCD of its node timesteps; an
    empty graph 1e-3.  (This used to read a ``_base_dt`` attribute nothing
    set and fall back to the smallest node timestep, MADD-ANO-097.)
    """
    from maddening.core._graph_specs import _step_duration  # noqa: PLC0415

    try:
        return float(graph_manager.timestep)
    except (AttributeError, RuntimeError):
        pass
    dts = {name: dt for name, dt in _node_timesteps(graph_manager).items() if dt > 0}
    return float(_step_duration(dts)) if dts else 1.0e-3


def _deterministic_token(parts: Iterable[str]) -> str:
    """Build a stable, GUID-shaped token from a list of strings.

    We don't use Python's ``uuid`` because the token must be a pure
    function of the graph's structural fingerprint (any FMU loader
    refuses to instantiate when the token doesn't match the runtime
    DLL's compile-time token).  See FMI 3.0 §2.2.3.
    """
    import hashlib  # noqa: PLC0415 — stdlib lazy import
    h = hashlib.sha256()
    for part in parts:
        h.update(part.encode("utf-8"))
        h.update(b"\0")
    digest = h.hexdigest()
    # Format as 8-4-4-4-12 GUID for tooling that pattern-matches it.
    return f"{digest[:8]}-{digest[8:12]}-{digest[12:16]}-{digest[16:20]}-{digest[20:32]}"


#: The attributes of a variable the instantiation token does *not* cover,
#: with why.  Every other field of :class:`FMIVariable` is hashed
#: (:func:`_token_part`); ``tests/fmi`` holds the two lists to the dataclass,
#: so a field added to it has to be put in one of them.
_NOT_IN_THE_TOKEN = {
    "description": "free text; nothing computes with it and the bridge does not check it",
    "node": "the graph address of the variable, not written to the XML (the name is)",
    "field": "the graph address of the variable, not written to the XML (the name is)",
}


def _token_part(v: "FMIVariable") -> str:
    """What the instantiation token hashes of one variable: everything its
    ``modelDescription.xml`` element advertises that an importer or the
    bridge acts on -- name, value reference, type, causality, variability,
    shape, start, min, max, clocks, a clock's interval and the unit."""
    return (f"{v.name}:{v.value_reference}:{v.dtype}:{v.causality}:{v.variability}:"
            f"{v.shape!r}:{v.start}:{v.min!r}:{v.max!r}:{v.clocks!r}:{v.interval_decimal!r}:"
            f"{v.unit!r}")


def _owner(var: "FMIVariable") -> str:
    """``"the <causality> of node 'n', field 'f'"`` for a clash message."""
    if var.node is None:
        return f"the {var.causality} {var.name!r}"
    return f"the {var.causality} of node {var.node!r}, field {var.field!r}"


def _selected_output_pairs(selected_outputs: Any) -> set[tuple[str, str]]:
    """``selected_outputs`` as a set of ``(node, field)`` name pairs.

    Raises
    ------
    ValueError
        If it is a string, or holds an entry that is not a pair of
        strings.  ``set((n, f) for (n, f) in selected_outputs)`` unpacked
        whatever it was given: ``"ab"`` as the pair ``("a", "b")``,
        ``"spring.position"`` as an unpacking error that named neither the
        argument nor its form.
    """
    if selected_outputs is None:
        return set()
    form = ("selected_outputs takes (node, field) pairs of names, such as "
            "[('spring', 'position')]")
    if isinstance(selected_outputs, (str, bytes)):
        raise ValueError(f"{form}; got the string {selected_outputs!r}")
    pairs: set[tuple[str, str]] = set()
    for entry in selected_outputs:
        if (isinstance(entry, (str, bytes)) or not isinstance(entry, (tuple, list))
                or len(entry) != 2 or not all(isinstance(part, str) for part in entry)):
            hint = ""
            if isinstance(entry, str) and "." in entry:
                node, _, field = entry.rpartition(".")
                hint = f" (for the output {entry!r}, pass ({node!r}, {field!r}))"
            raise ValueError(f"{form}; got the entry {entry!r}{hint}")
        pairs.add((entry[0], entry[1]))
    return pairs


def _refuse_outputs_nothing_exports(selected: set[tuple[str, str]], nodes: Any,
                                    include_evolving: bool) -> None:
    """Refuse a ``selected_outputs`` pair no output variable would come of.

    The outputs loop skips every pair it does not find, so a pair naming
    a node the graph does not have, a field its node does not have, or a
    node the stability filter keeps out exported nothing, without a word:
    ``selected_outputs=[("spring", "positon")]`` gave an FMU with no
    outputs at all.  (``selected_inputs`` has refused an unknown name since
    0.4.0's fix of the same silence.)

    Raises
    ------
    ValueError
        Naming every such pair with its node and field, and what the node
        or the graph does have.
    """
    problems: list[str] = []
    for node_name, field_name in sorted(selected):
        node_spec = (nodes or {}).get(node_name)
        if node_spec is None:
            problems.append(
                f"({node_name!r}, {field_name!r}): the graph has no node {node_name!r} "
                f"(its nodes: {sorted(nodes or {}) or ['(none)']})")
            continue
        node = getattr(node_spec, "node", node_spec)
        fields = list(node.state_fields())
        if field_name not in fields:
            problems.append(
                f"({node_name!r}, {field_name!r}): node {node_name!r} has no state field "
                f"{field_name!r} (its state fields: {sorted(fields) or ['(none)']})")
            continue
        cls_name = f"{type(node).__module__}.{type(node).__name__}"
        if not _ensure_stable_only_or_opt_in(cls_name, include_evolving):
            problems.append(
                f"({node_name!r}, {field_name!r}): node {node_name!r} is a "
                f"{type(node).__name__}, which is not a stability level this FMU exports "
                "(only STABLE nodes, or EVOLVING / PROVISIONAL ones with "
                "include_evolving=True, enter an FMU)")
    if problems:
        raise ValueError(
            "selected_outputs names output(s) this FMU cannot export, which would "
            "be left out of it without a word: " + "; ".join(problems) + ".  Fix the "
            "name, or leave the pair out.")


@stability(StabilityLevel.EVOLVING)
def build_model_description(
    graph_manager: Any,
    *,
    model_name: str,
    selected_inputs: Optional[Iterable[str]] = None,
    selected_outputs: Optional[Iterable[tuple[str, str]]] = None,
    include_evolving: bool = False,
    default_step_size: Optional[float] = None,
    include_parameters: bool = True,
    multi_clock: bool = False,
    model_identifier: Optional[str] = None,
) -> ModelDescription:
    """Build an FMI 3.0 :class:`ModelDescription` from a ``GraphManager``.

    Parameters
    ----------
    graph_manager : GraphManager
        A *compiled* graph, unchanged since its last ``compile()``.  The
        structure (nodes, edges, external inputs) is read at build time.
        Every pending ``node.params`` write is taken in first, as every
        graph entry point takes it in; one the compiled step bakes in (a
        structural value, such as ``HeatNode``'s ``stencil_order``) leaves
        the graph needing a recompile, and is refused with the rest (see
        Raises).  The description remembers the graph and its compile, and
        :class:`~maddening.fmi.tcp_bridge.FmuTcpBridge` refuses to serve it
        once the graph has changed or been compiled again.
    model_name : str
        Identifier the FMU will be called by.  Becomes ``modelName``
        in the XML.
    selected_inputs : iterable of str, optional
        FMU input variables to surface, as ``"<node>.<field>"`` of the
        graph's declared external inputs.  When ``None`` (default),
        every external input is included.  A name the graph does not
        declare is a ``ValueError`` (it used to export nothing in silence).
        A declared input left out is not an FMU variable, but the graph
        still reads it: the bridge holds it at zero on every step, as
        ``GraphManager.step`` does for an input its caller omits, and it is
        listed in :attr:`ModelDescription.held_inputs`.  A ``UserWarning``
        names every such input.  An input whose target node is not a
        stability level this FMU exports (see *include_evolving*) is never
        an FMU variable: it is held at zero and listed in ``held_inputs``
        the same way, and naming it here is a ``ValueError``.
    selected_outputs : iterable of (node, field) tuples, optional
        Which per-node state fields to expose as FMU outputs.  When
        ``None`` (default), every state field of every node is
        included.  A pair that names nothing this FMU can export is a
        ``ValueError`` naming the node and the field: a node the graph does
        not have, a field that is not one of the node's state fields, or a
        node whose stability level this FMU does not export (see
        *include_evolving*).  Such a pair used to export nothing in
        silence, so a misspelt field gave an FMU without that output; and
        an entry that is not a pair of names (``"spring.position"``, the
        form *selected_inputs* takes) is refused by name rather than
        unpacked letter by letter.
    include_evolving : bool, default False
        If ``True``, also include surfaces tagged
        ``@stability(EVOLVING)`` or ``PROVISIONAL``.  Default keeps
        the FMU's public surface minimal — only ``STABLE``-tagged
        sources/sinks contribute.  The filter is by node, and applies to a
        node's outputs, its parameters and the external inputs that target
        it alike; until 0.4.0's fix an input of an ``EXPERIMENTAL`` node
        was exported even though the node's outputs and parameters were
        not.
    default_step_size : float, optional
        Default fixed step size for the FMU's experiment block.  Defaults
        to one step of the graph, ``graph_manager.timestep``: the fastest
        node's timestep on a uniform-rate graph, and on a multi-rate graph
        the GCD of the timesteps as scheduled (a sub-cycling coupling
        group at its largest member timestep), which is what one sidecar
        step advances.  Another value is advertised as the FMU's
        communication step; a bridge serves it only if it is a whole
        number of graph steps.  The graph step itself is recorded as
        :attr:`ModelDescription.graph_timestep` either way.
    include_parameters : bool, default True
        Expose every leaf of ``graph_manager.params["nodes"]`` that the
        compiled step reads as a ``causality="parameter"``,
        ``variability="tunable"`` variable named ``<node>.params.<key>``
        (same stability filter as outputs), with ``description`` /
        ``unit`` from the node's :class:`~maddening.core.params.ParamSpec`.
        These are backed by the graph parameter pytree, so an importer that
        sets one changes the next step without a recompile.  The sidecar's
        Python API computes directional derivatives with respect to them
        with ``jax.jvp`` (``FmuSidecar.get_directional_derivative``); the
        FMU binary does not provide them: the description does not declare
        ``providesDirectionalDerivatives``, and the C wrapper's
        ``fmi3GetDirectionalDerivative`` returns ``fmi3Error``.  A leaf the
        step cannot read -- an ``initial_*``
        condition (the FMU's initial state is already built), a value a
        node consumed when it was constructed (``LBMPipeNode.pipe_radius``)
        or declares in ``static_data_deps`` (``WaveletAdaptiveNode.mass``),
        or one only an unconnected input would read -- is **not** exported:
        setting it would change nothing the FMU computes.  Those are listed
        with the reason in :attr:`ModelDescription.fixed_parameters`, which
        the bridge enforces.
    multi_clock : bool, default False
        Emit one FMI 3.0 ``<Clock>`` (``intervalVariability="constant"``)
        per distinct node timestep among the exported nodes, and tag every
        exported output and external input with the clock of its node
        (``clocks=`` attribute, ``variability="discrete"``): an importer
        then knows that a node on a 10x coarser rate only changes every
        10th master step.  A member of a sub-cycling coupling group is on
        its group's largest member timestep, the only rate at which its
        values change between steps.  Clocks are named ``clock_<k>`` in
        order of increasing interval.  Every interval is a whole number of
        graph steps (:attr:`ModelDescription.graph_timestep`).  With the
        default ``default_step_size`` (one graph step), the fastest clock
        equals the default step unless the timesteps do not divide each
        other (nodes at 0.002 and 0.003 run on a 0.001 step under clocks of
        0.002 and 0.003); a ``default_step_size`` given explicitly need not
        equal or divide any clock.  Off by default: no ``<Clock>``, no
        ``clocks=`` attribute, every output continuous.
    model_identifier : str, optional
        Emit a ``<CoSimulation modelIdentifier=...>`` element naming the
        FMU binary (``maddening.fmi.package`` uses ``"maddening_fmu"``).
        ``None`` (default) emits a description-only document.

    Returns
    -------
    ModelDescription

    Raises
    ------
    ValueError
        If *graph_manager* has never been compiled, or has changed since
        its last ``compile()``: a structural ``node.params`` write, a node,
        edge, external input or coupling group added or removed, or a
        node's ``static_data``.  The FMU's sidecar runs the compiled step,
        so the description would describe a model the FMU does not run
        (until 0.4.0's fix an FMU built over a pending structural write ran
        the old model while ``gm.run`` ran the new one).  Call
        ``compile()`` first.
        If *model_name* is exactly ``"NaN"``, ``"Infinity"`` or
        ``"-Infinity"``.  The name goes back to the importer in the
        bridge's ``hello`` reply, where the JSON codec refuses it
        (``MADD-ANO-010``); refusing it here is the only point at which
        the caller still has the name in its hand and can change it.
        See :data:`maddening.serialization.json_codec.NON_FINITE_TOKENS`.
        Also if *selected_inputs* names an input the graph does not
        declare, or one whose target node this FMU does not export; and
        if *selected_outputs* holds an entry that is not a ``(node,
        field)`` pair of names, or a pair naming a node the graph does not
        have, a field that is not a state field of its node, or a node
        this FMU does not export.

    Warns
    -----
    UserWarning
        If *selected_inputs* leaves out a declared external input, or an
        input targets a node this FMU does not export; the message names
        each one and says it is held at zero.
    """
    if model_name in NON_FINITE_TOKENS:
        # MADD-ANO-010's refusal is otherwise reached from the *reply*
        # side: ``FmuTcpBridge``'s hello carries ``model``, so an FMU with
        # this name answered every connection with an unencodable frame.
        # The bridge now turns that into an error reply rather than a dead
        # worker thread, but an error reply on every hello is still an
        # unusable FMU, and by then the caller is a C wrapper on the far
        # end of a socket with no way to act on the name.
        raise ValueError(
            f"model_name {model_name!r} spells a non-finite JSON token, which "
            f"the FMI wire encoding reserves (MADD-ANO-010): the bridge's "
            f"hello reply carries the model name, and a reply carrying this "
            f"string cannot be written as unambiguous JSON.  Name the model "
            f"something else (a different spelling, such as "
            f"{model_name.lower()!r}, is fine)."
        )
    # The FMU's sidecar runs the graph's *compiled* step
    # (``step_fn=gm._compiled_step``), so the description must describe the
    # model that step computes.  A structural node.params write pending since
    # the last compile is taken into the graph only as "dirty" (the next
    # entry point recompiles), and an FMU built over it ran the old model --
    # or the new one, if the step had not been traced yet -- while every
    # graph entry point ran the new one.  Refused rather than compiled here:
    # an export is an artefact, and compiling inside it would hide which
    # model it froze.
    stale = _graph_changed_since(graph_manager)
    if stale is not None:
        raise ValueError(
            f"build_model_description: {stale}.  The FMU's sidecar runs the graph's "
            "compiled step (step_fn=graph_manager._compiled_step), so this "
            "description would describe a model the FMU does not run.  Call "
            "graph_manager.compile(), then build the description, the sidecar and "
            "the bridge from the compiled graph without changing it in between."
        )
    # Inputs: read external-input edges from the graph manager.  The
    # graph manager exposes them via ``_external_input_specs`` (an
    # internal dict) — we accept a duck-typed view for tests.
    ext_specs = getattr(graph_manager, "_external_input_specs", None)
    if ext_specs is None:
        # A real GraphManager keeps ``_external_inputs`` (a list of
        # ExternalInputSpec); key them ``<node>.<field>`` -- unique, and
        # the same convention as outputs -- and borrow description /
        # units from the target node's boundary_input_spec().
        ext_specs = {}
        for ei in getattr(graph_manager, "_external_inputs", None) or []:
            target = getattr(ei, "target_node", None)
            fld = getattr(ei, "target_field", None)
            if target is None or fld is None:
                continue
            node_spec = (getattr(graph_manager, "_nodes", {}) or {}).get(target)
            node = getattr(node_spec, "node", node_spec)
            bis = {}
            try:
                bis = node.boundary_input_spec() if node is not None else {}
            except Exception:  # noqa: BLE001 - descriptor is advisory
                bis = {}
            declared = bis.get(fld)
            raw_dtype = getattr(ei, "dtype", "float32")
            try:
                dtype_name = np.dtype(raw_dtype).name       # jnp.float32 -> "float32"
            except TypeError:
                dtype_name = str(raw_dtype)
            ext_specs[f"{target}.{fld}"] = _ExtView(
                target_node=target, target_field=fld,
                shape=tuple(getattr(ei, "shape", ()) or ()),
                dtype=dtype_name,
                description=getattr(declared, "description", "") or "",
                expected_units=getattr(declared, "expected_units", "") or "",
            )
    if isinstance(selected_inputs, str):
        raise ValueError(
            f"selected_inputs must be an iterable of input names, not the "
            f"string {selected_inputs!r}; pass [{selected_inputs!r}]")
    selected_input_keys = (
        set(selected_inputs) if selected_inputs is not None
        else set(ext_specs.keys())
    )
    unknown_inputs = sorted(selected_input_keys - set(ext_specs))
    if unknown_inputs:
        raise ValueError(
            f"selected_inputs names {unknown_inputs}, which the graph does not "
            f"declare; declared external inputs: {sorted(ext_specs) or ['(none)']}.  "
            "An unknown name would export nothing and leave the input it was "
            "meant to be held at zero; fix the name."
        )
    # The same for the outputs, before anything is built or warned about: a
    # pair no output would come of used to be skipped in silence.
    selected_output_set = _selected_output_pairs(selected_outputs)
    _refuse_outputs_nothing_exports(
        selected_output_set, getattr(graph_manager, "_nodes", {}) or {}, include_evolving)
    # The stability filter outputs and parameters go through applies to the
    # inputs too, by their target node: an input of a node this FMU does
    # not export (an EXPERIMENTAL one always; an EVOLVING or PROVISIONAL one
    # without include_evolving) used to enter the FMU as a settable
    # variable while that node's outputs and parameters were left out.  It
    # is held at zero, as a left-out input is.  A duck-typed view whose
    # node the graph does not hold is not judged.
    unexported_inputs: dict[str, str] = {}
    for ext_key, ext_spec in ext_specs.items():
        target_spec = (getattr(graph_manager, "_nodes", {}) or {}).get(
            getattr(ext_spec, "target_node", None))
        target = getattr(target_spec, "node", target_spec)
        if target is None:
            continue
        cls_name = f"{type(target).__module__}.{type(target).__name__}"
        if not _ensure_stable_only_or_opt_in(cls_name, include_evolving):
            unexported_inputs[ext_key] = type(target).__name__
    if selected_inputs is not None:
        refused = sorted(set(selected_inputs) & set(unexported_inputs))
        if refused:
            raise ValueError(
                f"selected_inputs names {refused}, input(s) of node(s) this FMU does "
                f"not export ({sorted({unexported_inputs[k] for k in refused})}: "
                "only STABLE nodes, or EVOLVING / PROVISIONAL ones with "
                "include_evolving=True, enter an FMU)")
    selected_input_keys -= set(unexported_inputs)
    held_inputs: dict[str, tuple[str, str, tuple[int, ...], str]] = {}
    for ext_key, ext_spec in ext_specs.items():
        if ext_key in selected_input_keys:
            continue
        held_dtype = getattr(ext_spec, "dtype", "float32")
        if not isinstance(held_dtype, str):
            held_dtype = getattr(held_dtype, "name", str(held_dtype))
        held_inputs[ext_key] = (
            str(getattr(ext_spec, "target_node", "") or ""),
            str(getattr(ext_spec, "target_field", "") or ""),
            tuple(getattr(ext_spec, "shape", ()) or ()),
            held_dtype,
        )
    if unexported_inputs:
        warnings.warn(
            f"build_model_description: the external input(s) "
            f"{sorted(unexported_inputs)} feed node(s) this FMU does not export "
            f"({sorted(set(unexported_inputs.values()))}: only STABLE nodes, or "
            "EVOLVING / PROVISIONAL ones with include_evolving=True, enter an "
            "FMU), so they are not FMU variables and are held at zero on every "
            "step, as GraphManager.step holds an input it is not given.  They "
            "are listed in ModelDescription.held_inputs.",
            UserWarning, stacklevel=2,
        )
    left_out = sorted(set(held_inputs) - set(unexported_inputs))
    if left_out:
        warnings.warn(
            f"build_model_description: selected_inputs leaves out the declared "
            f"external input(s) {left_out}, which will be held at "
            "zero on every step.  They are not FMU variables, so no importer "
            "can set them, but the graph still reads them; the bridge passes "
            "zero, as GraphManager.step does for an input it is not given.  "
            "They are listed in ModelDescription.held_inputs.",
            UserWarning, stacklevel=2,
        )

    variables: list[FMIVariable] = []
    next_vr = 1  # FMI uses 1-based valueReference

    # ----- Independent variable (FMI 3.0 §2.2.7 mandates exactly one) -----
    # Time is the universal independent variable for fixed-step / continuous
    # simulation.  FMU loaders (e.g. FMPy) refuse a modelDescription.xml
    # missing it.
    variables.append(FMIVariable(
        name="time",
        value_reference=next_vr,
        dtype="float64",
        causality="independent",
        variability="continuous",
        description="Simulation time (independent variable).",
        unit="s",
    ))
    next_vr += 1

    # ----- Clocks (multi-rate export) -----
    nodes = getattr(graph_manager, "_nodes", {})
    clock_vr_of_dt: dict[float, int] = {}
    node_clock: dict[str, int] = {}
    if multi_clock:
        scheduled = _node_timesteps(graph_manager)
        dts: dict[float, list[str]] = {}
        for node_name, node_spec in nodes.items():
            node = getattr(node_spec, "node", node_spec)
            cls_name = f"{type(node).__module__}.{type(node).__name__}"
            if not _ensure_stable_only_or_opt_in(cls_name, include_evolving):
                continue
            # The scheduled timestep, not the node's own: a sub-cycled
            # member's outputs change once per macro step of its group.
            dt = scheduled[node_name]
            dts.setdefault(dt, []).append(node_name)
        for k, dt in enumerate(sorted(dts)):
            variables.append(FMIVariable(
                name=f"clock_{k}",
                value_reference=next_vr,
                dtype=_CLOCK_DTYPE,
                causality="input",
                variability="discrete",
                description=(
                    f"Rate {dt!r} s: ticks when nodes "
                    f"{', '.join(sorted(dts[dt]))} update."
                ),
                interval_decimal=dt,
            ))
            clock_vr_of_dt[dt] = next_vr
            for n in dts[dt]:
                node_clock[n] = next_vr
            next_vr += 1

    def _clocked(node_name: str, dtype: str) -> tuple[tuple[int, ...], str]:
        """``(clocks, variability)`` for a variable of ``dtype`` owned by
        ``node_name``.

        FMI 3.0 allows ``variability="continuous"`` only for a float type:
        a Boolean or integer input or output is ``discrete``, or FMPy's
        model-structure check refuses the description (it did, once the
        start values of such variables were valid literals).
        """
        vr = node_clock.get(node_name)
        if vr is not None:
            return (vr,), "discrete"
        return (), ("continuous" if _fmi_kind(dtype) == "float" else "discrete")

    # ----- Inputs -----
    for ext_key, ext_spec in ext_specs.items():
        if ext_key not in selected_input_keys:
            continue
        dtype = getattr(ext_spec, "dtype", "float32")
        if not isinstance(dtype, str):
            dtype = getattr(dtype, "name", str(dtype))
        shape = tuple(getattr(ext_spec, "shape", ()) or ())
        unit = getattr(ext_spec, "expected_units", "") or ""
        clocks, variability = _clocked(str(getattr(ext_spec, "target_node", "")), dtype)
        # FMI 3.0 requires a start value on every input; the graph's own
        # default for an unset external input is zero, so advertise that,
        # spelled as the input's type spells zero ("false", "0", "0.0").
        n_elems = int(np.prod(shape)) if shape else 1
        variables.append(FMIVariable(
            name=ext_key,
            value_reference=next_vr,
            dtype=dtype,
            causality="input",
            variability=variability,
            description=getattr(ext_spec, "description", "") or "",
            unit=unit,
            node=str(getattr(ext_spec, "target_node", "") or ""),
            field=str(getattr(ext_spec, "target_field", "") or ""),
            shape=shape or None,
            clocks=clocks,
            start=" ".join([_xs_value(0, dtype)] * n_elems),
        ))
        next_vr += 1

    # ----- Outputs -----
    for node_name, node_spec in nodes.items():
        node = getattr(node_spec, "node", node_spec)
        node_class_name = (
            f"{type(node).__module__}.{type(node).__name__}"
        )
        if not _ensure_stable_only_or_opt_in(node_class_name, include_evolving):
            # Node's class isn't part of the public FMU surface yet.
            continue
        for field_name in node.state_fields():
            if selected_outputs is not None and \
                    (node_name, field_name) not in selected_output_set:
                continue
            initial = node.initial_state()[field_name]
            dtype = str(getattr(initial, "dtype", "float32"))
            shape = tuple(getattr(initial, "shape", ()) or ())
            clocks, variability = _clocked(node_name, dtype)
            variables.append(FMIVariable(
                name=f"{node_name}.{field_name}",
                value_reference=next_vr,
                dtype=dtype,
                causality="output",
                variability=variability,
                description=f"State field {field_name!r} of node "
                            f"{node_name!r}",
                node=node_name,
                field=field_name,
                shape=shape or None,
                clocks=clocks,
            ))
            next_vr += 1

    # ----- Parameters (graph parameter pytree) -----
    fixed_parameters: dict[str, str] = {}
    if include_parameters:
        used = {v.name for v in variables}
        node_params = getattr(graph_manager, "params", {}) or {}
        node_params = node_params.get("nodes", {}) if isinstance(node_params, dict) else {}
        # Declared callable so the `callable()` guard narrows to something
        # whose return is `Any` rather than `object` (see maddening.core.node).
        specs_fn: Callable[..., Any] | None = getattr(
            graph_manager, "param_specs", None)
        all_specs = specs_fn().get("nodes", {}) if callable(specs_fn) else {}
        # A knob the running step never reads is not advertised: an
        # importer would set it, read it back and see its value, and the
        # FMU would keep computing with the old one.
        unread_fn: Callable[..., Any] | None = getattr(
            graph_manager, "_param_leaves_the_step_cannot_read", None)
        unread = unread_fn() if callable(unread_fn) else {}
        for node_name, leaves in node_params.items():
            node_spec = nodes.get(node_name)
            node = getattr(node_spec, "node", node_spec)
            node_class_name = f"{type(node).__module__}.{type(node).__name__}"
            if not _ensure_stable_only_or_opt_in(node_class_name, include_evolving):
                for key in leaves:
                    fixed_parameters[f"{node_name}.params.{key}"] = (
                        f"{type(node).__name__} is not a stability level this "
                        "FMU exports (STABLE, or EVOLVING / PROVISIONAL with "
                        "include_evolving=True), so none of its variables are "
                        "part of the FMU"
                    )
                continue
            node_specs = all_specs.get(node_name, {})
            for key, leaf in leaves.items():
                # Own namespace, mirroring params["nodes"][node][key]: a
                # parameter may share its key with a state field (a
                # node's initial position, say) and must not clash with
                # the "<node>.<field>" output.
                name = f"{node_name}.params.{key}"
                if (node_name, key) in unread:
                    fixed_parameters[name] = unread[(node_name, key)]
                    continue
                if name in used:  # pragma: no cover - defensive
                    raise ValueError(f"FMU variable name clash: {name!r}")
                used.add(name)
                spec = node_specs.get(key)
                dtype = str(getattr(leaf, "dtype", "float32"))
                shape = tuple(getattr(leaf, "shape", ()) or ())
                flat = np.asarray(leaf).ravel()
                start = " ".join(_xs_value(x, dtype) for x in flat)
                lo, hi, unit = _parameter_envelope(spec, dtype)
                variables.append(FMIVariable(
                    name=name,
                    value_reference=next_vr,
                    dtype=dtype,
                    causality="parameter",
                    variability="tunable",
                    # The (node, key) pair, so nothing re-splits the name:
                    # a node named "rig.params.v2" spells
                    # "rig.params.v2.params.elasticity".
                    node=node_name,
                    field=key,
                    description=(
                        (spec.description if spec is not None and spec.description else "")
                        or f"Parameter {key!r} of node {node_name!r}"
                    ),
                    unit=unit,
                    shape=shape or None,
                    start=start,
                    min=lo,
                    max=hi,
                ))
                next_vr += 1

    # ----- Name uniqueness -----
    # FMI requires every variable name to be unique.  A graph node name
    # may contain a '.', which FMI reads as a name-space separator, so two
    # different (node, field) pairs can spell the same FMU name -- the one
    # ambiguity carrying ``node``/``field`` on the variable cannot resolve.
    # Refuse the export naming both owners instead of writing an FMU whose
    # variables an importer cannot tell apart.
    seen: dict[str, FMIVariable] = {}
    for var in variables:
        clash = seen.get(var.name)
        if clash is not None:
            raise ValueError(
                f"FMU variable name clash: {var.name!r} would name both "
                f"{_owner(clash)} and {_owner(var)}.  FMI variable names must "
                "be unique and a '.' in a node name is not distinguishable "
                "from the separator; rename one of them."
            )
        seen[var.name] = var

    # ----- Defaults -----
    # One graph step, recorded separately from the advertised step: a
    # caller may advertise a coarser communication step, and the bridge
    # still has to know what one sidecar step covers.
    graph_timestep = _master_timestep(graph_manager)
    if default_step_size is None:
        default_step_size = graph_timestep

    # Deterministic instantiationToken — depends on the schema, so
    # the FMU loader refuses mismatched schemas at instantiation.  It
    # covers every attribute of a variable that changes what the FMU does
    # or advertises -- the start values and bounds included: the bridge
    # starts every instance at its own description's starts, so an FMU
    # packaged from a graph with stiffness 30 used to instantiate, fmi3OK,
    # against a bridge serving the same structure at 45, while its
    # modelDescription.xml said 30.  And the unit: the bridge holds its
    # description to the graph's unit (it refuses to start once a
    # parameter's unit has changed), so the unit is advertised like the
    # bounds, and an FMU packaged before stiffness was re-declared from N/m
    # to kN/m used to instantiate against the bridge serving kN/m.  The
    # description text is not covered: nothing computes with it.
    token = _deterministic_token([
        model_name,
        *[_token_part(v) for v in variables],
        f"step:{default_step_size}",
    ])

    md = ModelDescription(
        model_name=model_name,
        instantiation_token=token,
        variables=variables,
        default_step_size=default_step_size,
        co_simulation_model_identifier=model_identifier,
        fixed_parameters=fixed_parameters,
        held_inputs=held_inputs,
        graph_timestep=graph_timestep,
    )
    generation = getattr(graph_manager, "_compile_generation", None)
    if callable(getattr(graph_manager, "_check_static_data_dirty", None)) \
            and isinstance(generation, int):
        md._graph = weakref.ref(graph_manager)
        md._graph_generation = generation
    return md


__all__ = [
    "FMIVariable",
    "ModelDescription",
    "build_model_description",
]
