#!/usr/bin/env python
"""Generate the API stability report from the @stability registry.

Imports the public API surface so every ``@stability``-decorated class
or function fires its decorator, populating the registry, then writes
a Markdown table to ``docs/developer_guide/stability_report.md``.

This script is called by the documentation build (see the
``stability-report`` Make target in ``docs/Makefile``) and as part of
the v0.3.0 release verification gate.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Force CPU JAX so the import doesn't try to allocate a GPU at doc-build time.
os.environ.setdefault("JAX_PLATFORMS", "cpu")

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
sys.path.insert(0, str(SRC))

# Surfaces we want enumerated.  Importing them ensures @stability fires.
import maddening  # noqa: F401
import maddening.core.graph_manager  # noqa: F401
import maddening.core.node  # noqa: F401
import maddening.core.edge  # noqa: F401
import maddening.core.static_data  # noqa: F401
import maddening.core.coupling  # noqa: F401
import maddening.cloud.multigpu.sharded_node  # noqa: F401
import maddening.cloud.providers  # noqa: F401
import maddening.api.binary_encoder  # noqa: F401
import maddening.nodes  # noqa: F401
import maddening.surrogates  # noqa: F401

from maddening.core.compliance.metadata import StabilityLevel
from maddening.core.compliance.stability import (
    _STABILITY_REGISTRY,
    generate_stability_report,
)


_HEADER = """\
# Stability Report

Generated by ``scripts/generate_stability_report.py``.  Refreshed at
release time as part of the v0.3.0+ verification gate (see
``plans/MADDENING_v0.3.0_PLAN.md`` §A2).

Each public surface is tagged via ``@stability`` and registered at
import time.  Levels:

| Level | Meaning |
|---|---|
| ``stable`` | Locked at 1.0.0 — backwards-incompatible change needs a major bump. |
| ``evolving`` | Settled wire format / signature, additions allowed. |
| ``provisional`` | Synonym for ``evolving``, retained for pre-v0.3.0 surfaces. |
| ``experimental`` | May break in any minor release. Opt-in only. |
| ``internal`` | Implementation detail. Not part of the public API. |
| ``deprecated`` | Scheduled for removal. |

"""


def main() -> int:
    out_dir = REPO_ROOT / "docs" / "developer_guide"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "stability_report.md"

    body = generate_stability_report()
    # Strip the report's own "# Stability Report" header — _HEADER provides ours.
    body_lines = body.splitlines()
    if body_lines and body_lines[0].startswith("# Stability Report"):
        body_lines = body_lines[1:]
        # drop the blank line that follows
        if body_lines and not body_lines[0].strip():
            body_lines = body_lines[1:]
    body = "\n".join(body_lines)

    out_path.write_text(_HEADER + body)

    n = len(_STABILITY_REGISTRY)
    n_stable = sum(1 for v in _STABILITY_REGISTRY.values() if v == StabilityLevel.STABLE)
    n_evolving = sum(1 for v in _STABILITY_REGISTRY.values()
                     if v in (StabilityLevel.EVOLVING, StabilityLevel.PROVISIONAL))
    n_experimental = sum(1 for v in _STABILITY_REGISTRY.values()
                         if v == StabilityLevel.EXPERIMENTAL)
    print(
        f"Wrote {out_path}: {n} surfaces "
        f"({n_stable} stable, {n_evolving} evolving, "
        f"{n_experimental} experimental)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
